import React, { useEffect, useState } from 'react';
import { ArrowLeft, Clock3, Phone, UserRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { AppLayout } from '../components/layout/AppLayout';
import { getCase, timeline } from '../data/mock/caseData';
import { VoiceCallPopup } from '../components/voice/VoiceCallPopup';
import { clearVoiceCallSnapshot, getVoiceCallSnapshot, updateVoiceCallSnapshot } from '../components/voice/voiceCallPersistence';

const CustomerResponseCard: React.FC = () => {
  const [response, setResponse] = useState<CustomerResponse | null>(() => { const saved = window.localStorage.getItem('customer-last-response'); return saved ? JSON.parse(saved) as CustomerResponse : null; });
  useEffect(() => { const sync = () => { const saved = window.localStorage.getItem('customer-last-response'); setResponse(saved ? JSON.parse(saved) as CustomerResponse : null); }; window.addEventListener('customer-response-change', sync); window.addEventListener('storage', sync); return () => { window.removeEventListener('customer-response-change', sync); window.removeEventListener('storage', sync); }; }, []);
  return response ? <div className="mb-3 rounded-xl border border-blue-100 bg-blue-50 p-3"><div className="flex items-center justify-between"><p className="text-xs font-bold text-blue-700">고객 최신 답변</p><span className="text-[11px] text-slate-500">{response.at}</span></div><p className="mt-2 text-sm font-semibold text-slate-800">{response.answer}</p><p className="mt-1 text-[11px] text-slate-500">AI 질문: {response.question}</p></div> : null;
};
const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-sm font-extrabold">{title}</h2>{title === 'CUSTOMER CONVERSATION MONITOR' && <CustomerResponseCard />}{children}</section>;
type CustomerResponse = { question: string; answer: string; at: string };

export const BankPage: React.FC = () => {
  const { caseId = 'VP-014' } = useParams(); const item = getCase(caseId);
  const [takeover, setTakeover] = useState(() => window.localStorage.getItem('human-takeover') === 'true');
  const [liveTimeline, setLiveTimeline] = useState<Array<[string, string, string]>>(timeline.map(([time, event, actor]) => [time, event, actor]));
  const [recordingUrl, setRecordingUrl] = useState<string | null>(null);
  const [bankCallOpen, setBankCallOpen] = useState(() => getVoiceCallSnapshot('bank').open);
  const setCallOpen = (open: boolean) => { updateVoiceCallSnapshot('bank', { open }); setBankCallOpen(open); };
  const closeBankCall = () => { clearVoiceCallSnapshot('bank'); setBankCallOpen(false); };
  const [currentTime, setCurrentTime] = useState(() => new Date().toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' }));
  useEffect(() => { const timer = window.setInterval(() => setCurrentTime(new Date().toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })), 1000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { window.localStorage.setItem('fds-risk', 'HIGH · 신규 수취인'); window.dispatchEvent(new Event('fds-risk-change')); }, []);
  const toggleTakeover = () => { const next = !takeover; setTakeover(next); window.localStorage.setItem('human-takeover', String(next)); window.dispatchEvent(new Event('human-takeover-change')); setLiveTimeline((current) => [[currentTime, next ? '담당자가 Case에 참여' : '담당자 참여가 종료됨', 'human'], ...current]); };
  const handleCallStarted = () => setLiveTimeline((current) => [[currentTime, '음성 통화 연결', 'voice'], ...current]);
  const handleRecordingReady = (url: string) => { setRecordingUrl(url); setLiveTimeline((current) => [[currentTime, '음성 통화 녹음 저장', 'voice'], ...current]); };

  return <AppLayout><div className="mx-auto max-w-6xl py-8 lg:ml-64">
    {takeover && <div className="mb-4 flex items-center justify-between rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-bold text-amber-800"><span>담당자가 Case에 참여 중입니다.</span><span className="text-xs">소비자 화면에도 실시간 반영</span></div>}
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link to={`/cases/${caseId}`} className="inline-flex items-center gap-1 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Case로 돌아가기</Link><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setCallOpen(true)} className="inline-flex items-center gap-1.5 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white shadow-sm transition hover:bg-emerald-700"><Phone size={14}/> 음성 통화 요청</button><button onClick={toggleTakeover} className={`rounded-xl px-3 py-2 text-xs font-bold ${takeover ? 'bg-amber-100 text-amber-700' : 'bg-slate-900 text-white'}`}>{takeover ? '담당자 참여 중' : 'Human Takeover'}</button><button className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold">금융조치 검토</button></div></div>
    <div className="mb-6"><p className="mb-2 text-xs font-bold text-blue-600">BANK FRAUD CASE WORKSPACE</p><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-black">#{item.id} · {item.risk}</h1><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{item.status}</span></div><p className="mt-2 text-sm text-slate-500">{item.type} · 담당자 확인 · 마지막 이벤트 {item.updatedAt}</p></div>
    <section className="mb-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-extrabold">참여자</h2><span className="text-xs font-bold text-emerald-600">실시간 참여 상태</span></div><div className="grid gap-3 sm:grid-cols-3">{[['모니터링 담당자', '김○○', true], ['중간확인자', '이○○', true], ['금융조치 담당자', '박○○', takeover]].map(([role, name, active]) => <div key={role as string} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3"><div className={`grid h-9 w-9 place-items-center rounded-full ${active ? 'bg-emerald-100 text-emerald-600' : 'bg-slate-200 text-slate-400'}`}><UserRound size={17}/></div><div className="min-w-0"><p className="truncate text-xs font-bold text-slate-700">{role as string}</p><p className="mt-0.5 text-[11px] text-slate-500">{name as string}</p></div><span className={`ml-auto shrink-0 text-[11px] font-extrabold ${active ? 'text-emerald-600' : 'text-slate-400'}`}>{active ? '참여 중' : '대기 중'}</span></div>)}</div></section>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_1fr_1fr]"><Section title="LIVE CASE BRIEF"><div className="rounded-xl border border-rose-200 bg-rose-50 p-4"><div className="flex items-center justify-between"><p className="text-xs font-bold text-rose-600">FDS RISK</p><span className="h-2 w-2 animate-pulse rounded-full bg-rose-500"/></div><p className="mt-2 text-lg font-black text-rose-800">HIGH · 신규 수취인</p></div><div className="mt-4 rounded-xl border border-blue-100 bg-blue-50/60 p-4"><p className="text-xs font-bold text-blue-700">사건 요약</p><p className="mt-2 text-sm font-semibold leading-7 text-slate-800">{item.summary}</p></div><div className="mt-4 rounded-xl border border-slate-100 bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">피해자 상황 정보</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><p className="text-[11px] text-slate-400">현재 확인 상태</p><p className="mt-1 text-sm font-bold text-slate-700">{item.victimStatus}</p></div><div><p className="text-[11px] text-slate-400">송금 여부</p><p className="mt-1 text-sm font-bold text-slate-700">{item.transferred ? '송금함' : '송금하지 않음'}</p></div><div><p className="text-[11px] text-slate-400">요구·피해 금액</p><p className="mt-1 text-sm font-bold text-slate-700">{item.amount || '확인 필요'}</p></div><div><p className="text-[11px] text-slate-400">고객 상황</p><p className="mt-1 line-clamp-2 text-sm font-bold text-slate-700">{item.consumerInfo}</p></div></div></div></Section><Section title="INVESTIGATION PLANNER"><div className="mb-3 rounded-xl border border-blue-100 bg-blue-50 p-3"><div className="flex justify-between text-xs font-bold text-blue-800"><span>P0 Auto Triage</span><span>4 / 6</span></div><div className="mt-2 h-1.5 rounded-full bg-blue-100"><div className="h-1.5 w-2/3 rounded-full bg-blue-600"/></div></div>{['송금 여부 확인', '개인정보·인증번호 노출', '설치 앱 및 원격제어 여부'].map((question, index) => <div key={question} className="mb-2 flex items-center justify-between rounded-lg border border-slate-100 p-3 text-xs"><span>{question}</span><button className="rounded-md bg-slate-900 px-2 py-1 text-[10px] font-bold text-white">{index === 0 ? '전송' : '확인'}</button></div>)}</Section><Section title="VERIFICATION MATRIX"><div className="space-y-3">{[['기관 사칭 여부', '불일치', '공식 대표번호'], ['금액 요구 여부', '미확인', '기관 확인 필요'], ['수취계좌 신규 여부', '확인됨', 'FDS Snapshot']].map(([label, status, evidence]) => <div key={label} className="rounded-xl border border-slate-100 p-3"><div className="flex justify-between text-xs font-bold"><span>{label}</span><span className={status === '불일치' ? 'text-rose-600' : 'text-amber-600'}>{status}</span></div><p className="mt-1 text-[11px] text-slate-400">근거: {evidence}</p></div>)}</div></Section></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.35fr]"><Section title="LIVE TIMELINE"><div className="mb-4 flex items-center justify-between rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><span className="inline-flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/> 실시간 업데이트</span><span>{currentTime}</span></div><div className="space-y-4">{liveTimeline.map(([time, event, actor], index) => <div key={`${time}-${event}-${index}`} className="flex gap-3 text-xs"><span className="w-12 shrink-0 font-bold text-slate-400">{time}</span><div><span className={`mr-2 inline-block h-2 w-2 rounded-full ${index === 0 ? 'animate-pulse bg-emerald-500' : 'bg-blue-500'}`}/><span className="font-semibold">{event}</span><span className="ml-2 text-slate-400">{actor}</span></div></div>)}</div></Section><Section title="CUSTOMER CONVERSATION MONITOR"><div className="space-y-3 rounded-xl bg-slate-50 p-4 text-xs"><p><b className="text-blue-600">AI</b> 이미 송금했나요?</p><p><b className="text-slate-600">고객</b> 아직 안 했어요.</p><p><b className="text-blue-600">AI</b> 개인정보나 인증번호를 전달했나요?</p></div><div className="mt-3 flex gap-2"><button className="flex-1 rounded-lg border border-slate-200 py-2 text-xs font-bold">전체 대화</button><button className="flex-1 rounded-lg bg-slate-900 py-2 text-xs font-bold text-white">{takeover ? '직원 메시지' : 'Resume AI'}</button></div></Section></div>
    <p className="mt-4 inline-flex items-center gap-1 text-xs text-slate-400"><Clock3 size={13}/> AI는 조사를 지원하며 최종 금융조치는 담당자가 판단합니다.</p>
    {recordingUrl && <div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-4"><p className="text-xs font-extrabold text-blue-800">음성 통화 녹음</p><p className="mt-1 text-[11px] text-blue-700">LIVE TIMELINE의 ‘음성 통화 녹음 저장’ 이벤트에 연결됨</p><audio controls src={recordingUrl} className="mt-3 h-9 w-full" /></div>}
    <VoiceCallPopup open={bankCallOpen} role="bank" onClose={closeBankCall} onCallStarted={handleCallStarted} onRecordingReady={handleRecordingReady} />
  </div></AppLayout>;
};
