import React, { useEffect, useRef } from 'react';
import { Activity } from 'lucide-react';
import type { MvpEvent } from '../../services/mvpChatApi';

const labels: Record<string, string> = { CASE_CREATED: '사건 접수', MESSAGE_ADDED: 'AI 응답 생성', VERIFICATION_CREATED: '기관 확인 요청', VERIFICATION_UPDATED: '기관 확인 상태 변경', BANK_ACTION_ADDED: '은행 조치 기록', CASE_REPORT_FINALIZED: '보고서 확정' };
const descriptions: Record<string, string> = { CASE_CREATED: '분석 결과를 바탕으로 사건이 접수되었습니다.', MESSAGE_ADDED: '현재 상황을 바탕으로 응답이 생성되었습니다.', VERIFICATION_CREATED: '확인 대상에 대한 사실 확인 업무가 등록되었습니다.', VERIFICATION_UPDATED: '기관 확인 상태 또는 결과가 변경되었습니다.', BANK_ACTION_ADDED: '은행 대응 조치가 기록되었습니다.', CASE_REPORT_FINALIZED: '사건 정보를 기준으로 보고서가 확정되었습니다.' };
const colors: Record<string, string> = { CASE_CREATED: 'border-blue-400 bg-blue-50', MESSAGE_ADDED: 'border-violet-400 bg-violet-50', VERIFICATION_CREATED: 'border-purple-400 bg-purple-50', VERIFICATION_UPDATED: 'border-purple-400 bg-purple-50', BANK_ACTION_ADDED: 'border-slate-400 bg-slate-50', CASE_REPORT_FINALIZED: 'border-emerald-400 bg-emerald-50' };

export const CaseLiveLog: React.FC<{ events: MvpEvent[]; heightClassName?: string; onMessageEvent?: (messageId: string, channel?: string) => void }> = ({ events, heightClassName = 'min-h-[620px]', onMessageEvent }) => {
  const filtered = events.filter((event) => event.event_type in labels);
  const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const node = scrollRef.current; if (node) node.scrollTop = node.scrollHeight; }, [filtered.length]);
  return <aside className={`flex ${heightClassName} min-h-0 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm`}><header className="flex items-center gap-2 border-b border-slate-100 px-4 py-4"><Activity size={17} className="text-blue-600"/><h2 className="text-sm font-black">사건 진행 현황</h2></header><div ref={scrollRef} className="flex-1 space-y-2 overflow-y-auto p-4">{filtered.length === 0 && <p className="rounded-xl bg-slate-50 p-4 text-xs text-slate-500">주요 진행 사항이 아직 없습니다.</p>}{filtered.map((event) => { const messageId = typeof event.payload.message_id === 'string' ? event.payload.message_id : null; const channel = typeof event.payload.channel === 'string' ? event.payload.channel : undefined; const content = <><div className="flex items-center justify-between gap-2"><p className="text-xs font-extrabold text-slate-800">{labels[event.event_type]}</p><time className="text-[10px] text-slate-400">{new Date(event.occurred_at).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })}</time></div><p className="mt-1 text-[11px] leading-5 text-slate-600">{descriptions[event.event_type]}</p></>; const className = `w-full rounded-r-lg border-l-2 p-2 pl-3 text-left ${colors[event.event_type] ?? 'border-slate-200 bg-white'}`; return messageId ? <button key={event.event_id} onClick={() => onMessageEvent?.(messageId, channel)} className={`${className} hover:brightness-95`}>{content}</button> : <article key={event.event_id} className={className}>{content}</article>; })}</div></aside>;
};
