import React, { useEffect, useRef } from 'react';
import { Activity } from 'lucide-react';
import type { MvpEvent } from '../../services/mvpChatApi';

const eventLabel: Record<string, string> = { CASE_CREATED: 'Case 생성', MESSAGE_ADDED: 'CaseCopilot 응답 생성', VERIFICATION_CREATED: '기관 검증 요청', VERIFICATION_UPDATED: '기관 검증 상태 변경', BANK_ACTION_ADDED: '은행 조치 기록', CASE_REPORT_FINALIZED: '보고서 작성' };
const eventDescription: Record<string, string> = { CASE_CREATED: '분석 결과를 바탕으로 Case가 생성되었습니다.', MESSAGE_ADDED: '현재 피해 상황과 미확인 항목을 바탕으로 AI 응답이 생성되었습니다.', VERIFICATION_CREATED: '사칭 주장 또는 확인 대상에 대한 사실 확인 업무가 등록되었습니다.', VERIFICATION_UPDATED: '기관 검증의 진행 상태 또는 확인 결과가 변경되었습니다.', BANK_ACTION_ADDED: '은행 대응 조치가 Case에 기록되었습니다.', CASE_REPORT_FINALIZED: '현재 Case 정보를 기준으로 보고서가 확정되었습니다.' };

export const CaseLiveLog: React.FC<{ events: MvpEvent[]; heightClassName?: string; onMessageEvent?: (messageId: string, channel?: string) => void }> = ({ events, heightClassName = 'min-h-[620px]', onMessageEvent }) => {
  const filtered = events.filter((event) => event.event_type in eventLabel);
  const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const node = scrollRef.current; if (node) node.scrollTop = node.scrollHeight; }, [filtered.length]);
  return <aside data-case-live-log className={`flex ${heightClassName} min-h-0 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm`}><header className="flex items-center gap-2 border-b border-slate-100 px-4 py-4"><Activity size={17} className="text-blue-600"/><h2 className="text-sm font-black">Case Live Log</h2></header><div ref={scrollRef} className="flex-1 space-y-3 overflow-y-auto p-4">{filtered.length === 0 && <p className="rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">기록할 주요 Case 이벤트가 아직 없습니다.</p>}{filtered.map((event) => { const messageId = typeof event.payload.message_id === 'string' ? event.payload.message_id : null; const channel = typeof event.payload.channel === 'string' ? event.payload.channel : undefined; const content = <><div className="flex items-center justify-between gap-2"><p className="text-xs font-extrabold text-slate-800">{eventLabel[event.event_type]}</p><time className="shrink-0 text-[10px] text-slate-400">{new Date(event.occurred_at).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })}</time></div><p className="mt-1 text-[11px] leading-5 text-slate-500">{eventDescription[event.event_type]}</p></>; return messageId ? <button key={event.event_id} onClick={() => onMessageEvent?.(messageId, channel)} className="w-full border-l-2 border-blue-300 pl-3 text-left transition hover:rounded-r-lg hover:bg-blue-50 hover:pr-2"><>{content}</></button> : <article key={event.event_id} className="border-l-2 border-slate-200 pl-3">{content}</article>; })}</div></aside>;
};
