import React, { FormEvent, useEffect, useRef, useState } from 'react';
import { Bot, Paperclip, Send, Share2, ShieldCheck, UserRound } from 'lucide-react';
import type { MvpMessage } from '../../services/mvpChatApi';

interface ChatWorkspaceProps {
  title: string; description: string; channelLabel: string; messages: MvpMessage[]; placeholder: string;
  currentUserId: string; theme?: 'light' | 'dark'; sending?: boolean; onSend: (content: string) => Promise<void>; quickActions?: Array<{ label: string; prompt: string }>; onShareMessage?: (message: MvpMessage) => Promise<void>; sharingMessageId?: string | null; draftStorageKey?: string; heightClassName?: string; focusMessageId?: string | null;
}
const actorLabel: Record<MvpMessage['actor_type'], string> = { CUSTOMER: '고객', BANK_STAFF: '은행 담당자', CUSTOMER_AGENT: 'Customer Agent', BANK_AGENT: 'CaseCopilot', VERIFICATION: '기관 검증', SYSTEM: '시스템' };

export const ChatWorkspace: React.FC<ChatWorkspaceProps> = ({ title, description, channelLabel, messages, placeholder, currentUserId, theme = 'light', sending = false, onSend, quickActions = [], onShareMessage, sharingMessageId, draftStorageKey, heightClassName = 'min-h-[620px]', focusMessageId }) => {
  const [draft, setDraft] = useState(() => draftStorageKey ? localStorage.getItem(draftStorageKey) ?? '' : '');
  const scrollRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (draftStorageKey) localStorage.setItem(draftStorageKey, draft); }, [draft, draftStorageKey]);
  useEffect(() => { const node = scrollRef.current; if (node) node.scrollTop = node.scrollHeight; }, [messages.length]);
  useEffect(() => { if (!focusMessageId) return; document.getElementById(`message-${focusMessageId}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }, [focusMessageId]);
  const sendDraft = async () => { const content = draft.trim(); if (!content || sending) return; await onSend(content); setDraft(''); if (draftStorageKey) localStorage.removeItem(draftStorageKey); };
  const submit = async (event: FormEvent) => { event.preventDefault(); await sendDraft(); };
  const dark = theme === 'dark';
  return <section className={`flex ${heightClassName} min-h-0 flex-col overflow-hidden rounded-2xl border shadow-sm ${dark ? 'border-slate-700 bg-slate-950' : 'border-slate-200 bg-white'}`}>
    <header className={`border-b px-5 py-4 ${dark ? 'border-slate-800 bg-slate-950' : 'border-slate-100'}`}><div className="flex items-center justify-between gap-3"><div><h1 className={`text-base font-black ${dark ? 'text-white' : 'text-slate-900'}`}>{title}</h1><p className={`mt-1 text-xs ${dark ? 'text-slate-400' : 'text-slate-500'}`}>{description}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${dark ? 'bg-slate-800 text-slate-200' : 'bg-slate-100 text-slate-600'}`}>{channelLabel}</span></div></header>
    <div ref={scrollRef} className={`flex-1 space-y-4 overflow-y-auto p-4 sm:p-5 ${dark ? 'bg-slate-900' : 'bg-slate-50/70'}`} aria-live="polite">{messages.length === 0 && <div className={`rounded-2xl border border-dashed p-6 text-center text-sm ${dark ? 'border-slate-700 bg-slate-800 text-slate-400' : 'border-slate-200 bg-white text-slate-500'}`}>아직 대화가 없습니다.</div>}{messages.map((message) => { const mine = message.actor_user_id === currentUserId; const agent = message.actor_type === 'CUSTOMER_AGENT' || message.actor_type === 'BANK_AGENT'; const canShare = Boolean(onShareMessage && message.actor_type === 'BANK_AGENT' && message.message_kind === 'AI_RESPONSE' && message.visibility === 'AI_PRIVATE' && message.private_owner_user_id === currentUserId); return <article id={`message-${message.message_id}`} key={message.message_id} className={`scroll-mt-4 flex gap-2.5 rounded-xl transition ${focusMessageId === message.message_id ? 'bg-blue-100 p-2 ring-2 ring-blue-300' : ''} ${mine ? 'flex-row-reverse' : ''}`}><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${mine ? 'bg-blue-600 text-white' : agent ? 'bg-violet-200 text-violet-800' : 'bg-amber-100 text-amber-700'}`}>{agent ? <Bot size={16}/> : mine ? <UserRound size={16}/> : <ShieldCheck size={16}/>}</div><div className={`max-w-[82%] ${mine ? 'text-right' : ''}`}><p className={`mb-1 text-[11px] font-bold ${dark ? 'text-slate-400' : 'text-slate-500'}`}>{message.actor_display_name || actorLabel[message.actor_type]}</p><div className={`whitespace-pre-wrap rounded-2xl px-3.5 py-2.5 text-left text-sm leading-6 ${mine ? 'rounded-tr-sm bg-blue-600 text-white' : dark ? 'rounded-tl-sm border border-slate-700 bg-slate-800 text-slate-100' : 'rounded-tl-sm border border-slate-200 bg-white text-slate-700'}`}>{message.content}</div>{canShare && <button type="button" disabled={sharingMessageId === message.message_id} onClick={() => { if (onShareMessage) void onShareMessage(message); }} className={`mt-2 inline-flex items-center gap-1 rounded-lg border px-2 py-1 text-[11px] font-bold disabled:opacity-50 ${dark ? 'border-violet-500/50 bg-slate-800 text-violet-200' : 'border-blue-200 bg-white text-blue-700'}`}><Share2 size={12}/>{sharingMessageId === message.message_id ? '공유 중' : '팀에 공유'}</button>}<time className="mt-1 block text-[10px] text-slate-400">{new Date(message.created_at).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })}</time></div></article>; })}</div>
    <form onSubmit={submit} className={`border-t p-3 sm:p-4 ${dark ? 'border-slate-800 bg-slate-950' : 'border-slate-200 bg-white'}`}>{quickActions.length > 0 && <div className="mb-3 flex flex-wrap items-center gap-2"><span className="mr-1 text-[11px] font-bold text-slate-400">빠른 AI 요청</span>{quickActions.map((action) => <button key={action.label} type="button" disabled={sending} onClick={() => void onSend(action.prompt)} className={`rounded-full border px-2.5 py-1.5 text-[11px] font-bold disabled:opacity-50 ${dark ? 'border-violet-500/50 bg-slate-800 text-violet-200 hover:border-violet-300' : 'border-violet-200 bg-violet-50 text-violet-800 hover:border-violet-400'}`}>{action.label}</button>)}</div>}<div className={`flex items-end gap-2 rounded-2xl border p-2 focus-within:border-blue-500 focus-within:ring-2 focus-within:ring-blue-100 ${dark ? 'border-slate-700 bg-slate-900' : 'border-slate-200 bg-slate-50'}`}><button type="button" className="grid h-9 w-9 shrink-0 place-items-center rounded-xl text-slate-400" aria-label="첨부 기능 준비 중"><Paperclip size={18}/></button><textarea value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing) { event.preventDefault(); void sendDraft(); } }} rows={2} placeholder={placeholder} className={`min-h-[44px] flex-1 resize-none border-0 bg-transparent px-1 py-2 text-sm outline-none ${dark ? 'text-white placeholder:text-slate-500' : ''}`}/><button type="submit" disabled={!draft.trim() || sending} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-600 text-white disabled:opacity-40" aria-label="메시지 전송"><Send size={17}/></button></div><p className="mt-2 px-1 text-[11px] text-slate-400">Enter 전송 · Shift+Enter 줄바꿈 · 작성 중인 텍스트는 이 기기에 자동 저장됩니다.</p></form>
  </section>;
};
