import React, { FormEvent, useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, Bot, Check, ChevronDown, HelpCircle, Info, Paperclip, RefreshCw, Send, ShieldAlert, Volume2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { CaseBundleV2, MvpMessage } from '../../services/mvpChatApi';

type AiQuestion = { id: string; prompt: string; options: string[]; mode?: string };

const RecoveryGuide: React.FC = () => (
  <section className="rounded-xl border border-rose-200 bg-gradient-to-br from-rose-50 to-white p-4 shadow-sm">
    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-rose-700"><ShieldAlert size={21} /><h2 className="font-black">보이스피싱 피해 구제 안내</h2></div><button type="button" aria-label="피해구제 안내 닫기" className="text-xl leading-none text-slate-500">×</button></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-4">{[
      ['01', '즉시 연락', '계좌 이체·대출 등 금융사에 즉시 연락하여 지급정지 요청'], ['02', '증빙 확보', '통화 내용, 송금내역, 문자 등 관련 증빙을 확보'], ['03', '신고 접수', '경찰청(112) 또는 금융감독원에 피해 신고 접수'], ['04', '구제 신청', '금융감독원 또는 해당 금융사에 피해구제 신청'],
    ].map(([number, title, description]) => <div key={number} className="rounded-xl border border-rose-100 bg-white p-3"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-rose-50 text-xs font-black text-rose-600">{number}</span><p className="text-sm font-extrabold text-slate-800">{title}</p></div><p className="mt-2 text-xs leading-5 text-slate-600">{description}</p></div>)}</div>
    <div className="mt-3 rounded-xl border border-rose-100 bg-rose-100/60 px-3 py-2.5 text-xs leading-5 text-slate-700"><span className="mr-1 font-black text-rose-600">꼭 기억하세요!</span> 빠른 신고와 증빙 확보가 피해 구제에 가장 중요합니다.</div>
  </section>
);

const AiQuestionCard: React.FC<{ question: AiQuestion; answer?: string; sending: boolean; onChoose: (question: AiQuestion, answer: string) => void }> = ({ question, answer, sending, onChoose }) => (
  <article className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-blue-600 text-white shadow-md shadow-blue-200"><Bot size={20} /></div><div className="max-w-[92%] rounded-2xl rounded-tl-sm border border-slate-200 bg-white px-4 py-3 shadow-sm"><p className="text-sm font-bold leading-6 text-slate-800">{question.prompt}</p><div className="mt-3 flex flex-wrap gap-2">{question.options.map((option) => <button key={option} type="button" onClick={() => onChoose(question, option)} disabled={Boolean(answer) || sending} className={`rounded-xl border px-3 py-2 text-xs font-bold transition ${answer === option ? 'border-blue-500 bg-blue-50 text-blue-700 ring-1 ring-blue-200' : answer ? 'border-slate-100 bg-slate-50 text-slate-400' : 'border-slate-200 bg-white text-slate-600 hover:border-blue-300 hover:bg-blue-50 hover:text-blue-700'}`}>{answer === option && <Check size={13} className="mr-1 inline" />}{option}</button>)}</div>{answer && <p className="mt-2 text-xs font-semibold text-blue-600">선택한 답변: {answer}</p>}</div></article>
);

const progressIcon = (state: 'warning' | 'active' | 'pending') => state === 'warning' ? <div className="grid h-8 w-8 place-items-center rounded-full border border-amber-400 bg-amber-50 text-amber-600"><AlertTriangle size={16} /></div> : state === 'active' ? <div className="grid h-8 w-8 place-items-center rounded-full border-[3px] border-blue-600 bg-blue-50"><span className="h-2.5 w-2.5 rounded-full bg-blue-600" /></div> : <div className="grid h-8 w-8 place-items-center rounded-full border border-slate-300 bg-slate-50"><span className="h-3 w-3 rounded-full bg-slate-500" /></div>;

interface CustomerSafetyRoomProps { caseId: string; bundle: CaseBundleV2 | null; messages: MvpMessage[]; sending: boolean; onSend: (content: string) => Promise<void>; }

export const CustomerSafetyRoom: React.FC<CustomerSafetyRoomProps> = ({ caseId, bundle, sending, onSend }) => {
  const [draft, setDraft] = useState('');
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [expandedStep, setExpandedStep] = useState<string | null>(null);
  const [recoveryRequested, setRecoveryRequested] = useState(false);
  const currentCase = bundle?.case ?? {};
  const risk = String(currentCase.risk ?? 'HIGH');
  const initialBrief = String(currentCase.initial_brief ?? '현재 상황을 은행과 함께 확인하고 있습니다. 확인 전까지 송금하거나 인증정보를 제공하지 마세요.');
  const aiQuestions = useMemo<AiQuestion[]>(() => (bundle?.questions ?? []).map((question, index) => ({ id: String(question.question_id ?? question.id ?? `ai-question-${index}`), prompt: String(question.prompt ?? question.question ?? '').trim(), options: (question.options ?? question.choices ?? []).map(String).filter(Boolean), mode: question.mode })).filter((question) => question.prompt && question.options.length > 0 && (!question.mode || question.mode === 'ALL' || question.mode === (recoveryRequested ? 'RECOVERY' : 'PREVENT'))), [bundle?.questions, recoveryRequested]);
  const progressSteps = [
    { id: 'transfer', title: '송금 여부', description: answers.transfer ? `고객 답변: ${answers.transfer}` : '이미 송금했는지 확인이 필요합니다.', state: answers.transfer ? 'active' as const : 'warning' as const, badge: answers.transfer ? '답변 완료' : '확인 필요' },
    { id: 'personal', title: '개인정보 노출', description: answers.personal ? `고객 답변: ${answers.personal}` : '개인정보를 알려주거나 공유했는지 확인이 필요합니다.', state: answers.personal ? 'active' as const : 'warning' as const, badge: answers.personal ? '답변 완료' : '확인 필요' },
    { id: 'verification', title: '공식기관 검증', description: '기관 정보의 사실 여부를 공식 채널로 확인하고 있습니다.', state: 'active' as const, badge: '진행 중' },
    { id: 'bank', title: '은행 확인 및 조치', description: '추가 확인 후 은행 조치 여부를 검토합니다.', state: 'pending' as const, badge: '추가 확인 중' },
    { id: 'staff', title: '담당자 참여', description: '필요한 경우 은행 담당자가 직접 확인 및 안내를 진행합니다.', state: 'pending' as const, badge: '참여 대기 중' },
  ];
  const chooseAnswer = async (question: AiQuestion, answer: string) => { if (answers[question.id] || sending) return; await onSend(`${question.prompt}\n답변: ${answer}`); setAnswers((current) => ({ ...current, [question.id]: answer })); };
  const requestRecovery = async () => { if (recoveryRequested || sending) return; await onSend('이미 피해가 발생했습니다. 긴급 대응 및 피해구제 절차 안내를 요청합니다.'); setRecoveryRequested(true); };
  const returnToRegularConsultation = () => setRecoveryRequested(false);
  const submitDraft = async (event: FormEvent) => { event.preventDefault(); const content = draft.trim(); if (!content || sending) return; await onSend(content); setDraft(''); };

  return <main className="mx-auto max-w-[1640px] py-6 lg:ml-64 lg:py-8">
    <header className="mb-4 flex flex-wrap items-center justify-between gap-3 px-1"><Link to={`/cases/${caseId}`} className="inline-flex items-center gap-2 text-sm font-extrabold text-slate-800 hover:text-blue-700"><ArrowLeft size={17} /> Case로 돌아가기</Link>{recoveryRequested && <span className="inline-flex items-center gap-2 rounded-full bg-rose-600 px-4 py-2 text-xs font-extrabold text-white"><ShieldAlert size={15} /> 긴급상담 모드 활성화</span>}</header>
    <section className="mb-4 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-rose-200 bg-gradient-to-r from-rose-50 via-white to-rose-50 px-5 py-3.5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-rose-600 text-white"><ShieldAlert size={23} /></div><div><p className="font-black text-rose-700">{risk} RISK · PREVENT</p><p className="mt-0.5 text-sm text-slate-600">은행 확인 중 · #{caseId}</p></div></div><span className="rounded-xl border border-slate-200 bg-white px-5 py-2 text-xs font-extrabold text-slate-700">상황 확인 및 상담</span></section>
    <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1.25fr)_minmax(390px,0.95fr)]">
      <section className="flex min-h-[720px] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div className="flex items-center gap-3"><h1 className="text-lg font-black">{recoveryRequested ? '피해구제 상담' : 'AI 안전 상담'}</h1><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${recoveryRequested ? 'bg-rose-50 text-rose-600' : 'bg-blue-50 text-blue-600'}`}>{recoveryRequested ? '긴급상담 모드' : '실시간 상담 중'}</span></div><div className="flex items-center gap-2"><button type="button" aria-label="음성 안내" className="grid h-9 w-9 place-items-center rounded-full border border-slate-200 text-blue-600"><Volume2 size={17} /></button><button type="button" aria-label="상담 도움말" className="grid h-9 w-9 place-items-center rounded-full border border-slate-200 text-blue-600"><HelpCircle size={17} /></button></div></div>
        <div className="flex-1 space-y-4 overflow-y-auto bg-[linear-gradient(180deg,#ffffff_0%,#f8fbff_100%)] px-5 py-5">{recoveryRequested && <RecoveryGuide />}{aiQuestions.map((question) => <AiQuestionCard key={question.id} question={question} answer={answers[question.id]} sending={sending} onChoose={(selected, answer) => void chooseAnswer(selected, answer)} />)}</div>
        <form onSubmit={(event) => void submitDraft(event)} className="border-t border-slate-200 bg-white p-4"><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 focus-within:border-blue-400 focus-within:ring-2 focus-within:ring-blue-100"><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="궁금한 점을 입력하거나 버튼으로 답변해주세요." className="min-w-0 flex-1 bg-transparent px-2 py-2 text-sm outline-none" /><button type="button" aria-label="첨부 기능 준비 중" className="p-2 text-slate-400"><Paperclip size={20} /></button><button type="submit" disabled={!draft.trim() || sending} aria-label="상담 메시지 전송" className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 text-white disabled:opacity-40"><Send size={19} /></button></div><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full border border-slate-200 px-3 py-1.5 text-[11px] font-semibold text-slate-500">상담 종료</span><span className="rounded-full border border-slate-200 px-3 py-1.5 text-[11px] font-semibold text-slate-500">보이스피싱 예방법</span><span className="rounded-full border border-slate-200 px-3 py-1.5 text-[11px] font-semibold text-slate-500">＋ 안전 체크리스트</span></div></form>
      </section>
      <aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-3"><h2 className="text-lg font-black">AI 상황 요약</h2><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-600">AI Brief</span></div><HelpCircle size={19} className="text-blue-600" /></div><div className="flex gap-3 rounded-xl border border-blue-100 bg-blue-50/60 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-blue-600 text-white"><Bot size={20} /></div><div className="text-sm leading-6 text-slate-700"><p>• {recoveryRequested ? '피해 발생 가능성이 높습니다.' : initialBrief}</p><p>• {recoveryRequested ? '금융사 즉시 연락, 증빙 확보, 신고 접수를 권장합니다.' : '확인 전까지 송금하지 마세요.'}</p></div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-3"><h2 className="text-lg font-black">현재 대응 상황</h2><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[11px] font-bold text-blue-600">실시간 반영</span></div><span className="inline-flex items-center gap-1 text-xs font-bold text-blue-600"><RefreshCw size={14} /> 자동 갱신 중</span></div><div className="relative">{progressSteps.map((step, index) => <div key={step.id} className="relative flex gap-3 py-3"><div className="relative z-10">{progressIcon(step.state)}</div>{index !== progressSteps.length - 1 && <span className="absolute left-4 top-11 h-6 border-l border-dashed border-slate-300" />}<button type="button" onClick={() => setExpandedStep((current) => current === step.id ? null : step.id)} className="flex min-w-0 flex-1 items-start justify-between gap-3 text-left"><div><p className="text-sm font-extrabold text-slate-800">{step.title}</p><p className="mt-0.5 text-xs leading-5 text-slate-500">{step.description}</p>{expandedStep === step.id && <p className="mt-2 rounded-lg bg-slate-50 p-2 text-xs text-slate-600">고객님 답변과 담당자 검토 결과에 따라 갱신됩니다.</p>}</div><div className="flex shrink-0 items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${step.state === 'warning' ? 'bg-amber-50 text-amber-600' : step.state === 'active' ? 'bg-blue-50 text-blue-600' : 'bg-slate-100 text-slate-500'}`}>{step.badge}</span><ChevronDown size={16} className={`text-slate-400 ${expandedStep === step.id ? 'rotate-180' : ''}`} /></div></button></div>)}</div><p className="mt-2 flex items-center gap-1 text-[11px] text-slate-500"><Info size={13} /> 위 항목은 고객님 답변에 따라 실시간으로 변경됩니다.</p></section>
      <section className="rounded-2xl border border-rose-200 bg-rose-50 p-5 shadow-sm"><div className="flex items-center gap-3"><AlertTriangle className="text-rose-600" /><div><h2 className="font-black text-rose-700">{recoveryRequested ? '긴급상담 모드가 활성화되었습니다' : '이미 피해를 입으셨나요?'}</h2><p className="mt-0.5 text-xs text-slate-600">{recoveryRequested ? '피해구제 안내를 확인하고 일반 상담으로 돌아갈 수 있습니다.' : '송금·개인정보 노출 등 피해가 발생한 경우 즉시 대응해 드립니다.'}</p></div></div><button type="button" onClick={() => recoveryRequested ? returnToRegularConsultation() : void requestRecovery()} disabled={sending} className="mt-4 w-full rounded-xl bg-rose-600 px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50">{recoveryRequested ? '일반 상담으로 돌아가기' : '긴급 대응 시작'}</button><p className="mt-3 text-[11px] leading-5 text-rose-700">실제 금융 조치는 은행 담당자의 확인 후 진행됩니다.</p></section></aside>
    </div>
  </main>;
};
