import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, Pencil, RefreshCw, Trash2, X } from 'lucide-react';
import { casesApi } from '../api/cases';
import type { BankStaff, BankStaffColor } from '../api/types';

interface Props { onClose: () => void }
type Draft = Omit<BankStaff, 'staff_id' | 'is_self' | 'created_at' | 'updated_at'>;
const emptyDraft: Draft = { display_name: '', role_label: '고객 상담 담당자', position_title: '', status_text: '근무 중', status_color_key: 'GREEN', linked_user_id: null };
const rolePresets = ['FDS 모니터링 담당자', '고객 상담 담당자', '금융사기 대응 담당자', '사고 조사 담당자', '고객 보호 담당자', '보안 담당자'];
const positionPresets = ['사원', '주임', '대리', '과장', '차장', '부장', '팀장', '실장'];
const colorOptions: Array<{ key: BankStaffColor; label: string }> = [
  { key: 'GREEN', label: '초록' }, { key: 'BLUE', label: '파랑' }, { key: 'YELLOW', label: '노랑' }, { key: 'ORANGE', label: '주황' }, { key: 'RED', label: '빨강' }, { key: 'PURPLE', label: '보라' }, { key: 'GRAY', label: '회색' },
];

export const BankStaffManager: React.FC<Props> = ({ onClose }) => {
  const [items, setItems] = useState<BankStaff[]>([]); const [draft, setDraft] = useState<Draft>({ ...emptyDraft }); const [editingId, setEditingId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setItems(await casesApi.listBankStaff()); } catch (reason) { setError(reason instanceof Error ? reason.message : '담당자 목록을 불러오지 못했습니다.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter((item) => `${item.display_name} ${item.role_label} ${item.position_title || ''} ${item.status_text}`.toLowerCase().includes(query.trim().toLowerCase())), [items, query]);
  const reset = () => { setDraft({ ...emptyDraft }); setEditingId(null); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!draft.display_name.trim() || !draft.role_label.trim()) return; setSaving(true); setError(''); try { const normalized = { ...draft, display_name: draft.display_name.trim(), role_label: draft.role_label.trim(), position_title: draft.position_title?.trim() || null, status_text: draft.status_text.trim() || '근무 중' }; const saved = editingId ? await casesApi.updateBankStaff(editingId, normalized) : await casesApi.createBankStaff(normalized); setItems((current) => editingId ? current.map((item) => item.staff_id === saved.staff_id ? saved : item) : [...current, saved]); reset(); } catch (reason) { setError(reason instanceof Error ? reason.message : '담당자 정보를 저장하지 못했습니다.'); } finally { setSaving(false); } };
  const remove = async (item: BankStaff) => { if (!window.confirm(`${item.display_name} 담당자를 삭제할까요?`)) return; setSaving(true); setError(''); try { await casesApi.deleteBankStaff(item.staff_id); setItems((current) => current.filter((row) => row.staff_id !== item.staff_id)); if (editingId === item.staff_id) reset(); } catch (reason) { setError(reason instanceof Error ? reason.message : '담당자를 삭제하지 못했습니다.'); } finally { setSaving(false); } };
  return <div className="bank-staff-overlay" role="presentation"><section className="bank-staff-dialog" role="dialog" aria-modal="true" aria-labelledby="bank-staff-title">
    <header><div><p className="eyebrow">BANK STAFF DIRECTORY</p><h2 id="bank-staff-title">은행 담당자 관리</h2><small>은행 업무에 참여할 담당자를 등록·수정·관리합니다.</small></div><button type="button" className="icon-button" onClick={onClose} aria-label="닫기"><X size={18}/></button></header>
    <div className="bank-staff-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="이름·역할·직위·상태 검색"/><button type="button" onClick={() => void load()} disabled={loading}><RefreshCw size={14}/>새로고침</button></div>
    {error && <p className="bank-staff-error"><AlertCircle size={14}/>{error}</p>}
    <div className="bank-staff-content"><div className="bank-staff-list">{loading && <p className="bank-staff-empty">담당자 목록을 불러오는 중입니다…</p>}{!loading && filtered.length === 0 && <p className="bank-staff-empty">등록된 은행 담당자가 없습니다.<br/>오른쪽에서 첫 담당자를 등록해 주세요.</p>}{!loading && filtered.map((item) => <article className="bank-staff-card" key={item.staff_id}><div className="bank-staff-card-main"><strong>{item.display_name}</strong>{item.is_self && <span className="bank-staff-self">본인</span>}<span className="bank-staff-status" data-color={item.status_color_key}>{item.status_text}</span><small>{item.role_label}{item.position_title ? ` · ${item.position_title}` : ''}</small></div><div className="bank-staff-card-actions"><button type="button" onClick={() => { setEditingId(item.staff_id); setDraft({ display_name: item.display_name, role_label: item.role_label, position_title: item.position_title || '', status_text: item.status_text, status_color_key: item.status_color_key, linked_user_id: item.linked_user_id || null }); }}><Pencil size={13}/>수정</button><button type="button" className="danger" onClick={() => void remove(item)} disabled={saving}><Trash2 size={13}/>삭제</button></div></article>)}</div>
      <form className="bank-staff-form" onSubmit={save}><div className="bank-staff-form-heading"><h3>{editingId ? '담당자 수정' : '담당자 등록'}</h3>{editingId && <button type="button" onClick={reset}>새로 등록</button>}</div>
        <label>이름 *<input required value={draft.display_name} maxLength={100} onChange={(event) => setDraft({ ...draft, display_name: event.target.value })} placeholder="예: 김담당"/></label><label>직책 및 역할 *<input required list="bank-staff-role-presets" value={draft.role_label} maxLength={100} onChange={(event) => setDraft({ ...draft, role_label: event.target.value })}/></label><datalist id="bank-staff-role-presets">{rolePresets.map((item) => <option key={item} value={item}/>)}</datalist><label>직위<input list="bank-staff-position-presets" value={draft.position_title || ''} maxLength={100} onChange={(event) => setDraft({ ...draft, position_title: event.target.value })} placeholder="예: 대리"/></label><datalist id="bank-staff-position-presets">{positionPresets.map((item) => <option key={item} value={item}/>)}</datalist><label>현재 상태<input value={draft.status_text} maxLength={80} onChange={(event) => setDraft({ ...draft, status_text: event.target.value })} placeholder="예: 근무 중"/></label>
        <fieldset><legend>상태 색상</legend><div className="bank-staff-color-options">{colorOptions.map((item) => <button key={item.key} type="button" className={draft.status_color_key === item.key ? 'selected' : ''} data-color={item.key} onClick={() => setDraft({ ...draft, status_color_key: item.key })}>{item.label}</button>)}</div></fieldset><footer><button type="button" onClick={editingId ? reset : onClose}>취소</button><button type="submit" className="primary" disabled={saving || !draft.display_name.trim() || !draft.role_label.trim()}>{saving ? '저장 중…' : editingId ? '수정 저장' : '담당자 등록'}</button></footer>
      </form></div></section></div>;
};
