"""Generate the empty-DB/Docker bootstrap from versioned migrations.

Default checks freshness; --write regenerates the derived SQL artifact.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.apply_migrations import MVP_ROOT
from scripts.migration_manifest import ordered_migrations

OUTPUT = MVP_ROOT / 'database/01_mysql_csr_schema.sql'


def bootstrap_sql() -> str:
    parts = ["""-- GENERATED by backend/scripts/build_schema_bootstrap.py --write
-- Source of truth: backend/migrations/manifest.json (global filename order).
-- EMPTY DATABASE ONLY. Existing databases must use apply_migrations.py.
-- Includes the explicit 023 demo staff seed, but no Case/customer/chat data.
-- MySQL batch/Docker initialization stops on a nonempty database; never use --force.
SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET @csr_init_guard_sql = IF(
  (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE())=0,
  'DO 0',
  'SELECT * FROM information_schema.CSR_INIT_REQUIRES_EMPTY_DATABASE'
);
PREPARE csr_init_guard FROM @csr_init_guard_sql;
EXECUTE csr_init_guard;
DEALLOCATE PREPARE csr_init_guard;

CREATE TABLE schema_migrations (
    migration_name VARCHAR(255) PRIMARY KEY,
    applied_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
"""]
    for path in ordered_migrations():
        parts.append(f'\n-- Migration: {path.name}\n'+path.read_text(encoding='utf-8').strip()+'\n')
        parts.append(f"INSERT INTO schema_migrations (migration_name) VALUES ('{path.name}');\n")
    return '\n'.join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    expected = bootstrap_sql()
    if args.write:
        OUTPUT.write_text(expected, encoding='utf-8', newline='\n')
        print('Generated database/01_mysql_csr_schema.sql')
    elif OUTPUT.read_text(encoding='utf-8') != expected:
        raise SystemExit('Bootstrap is stale. Run build_schema_bootstrap.py --write.')
    else:
        print('Bootstrap matches all versioned migrations.')


if __name__ == '__main__':
    main()
