import React, { useEffect, useState } from 'react';
import { CheckSquare, Loader2, Plus, X } from 'lucide-react';
import { mvpChatApi, type CustomerQuestionCandidate } from '../../../services/mvpChatApi';

interface Props { caseId: string; requestedBy: string; onQueued: () => Promise<void> | void; onClose: () => void; }

export const QuestionRecommendationCard: React.FC<Props> = ({ caseId, requestedBy, onQueued, onClose }) => {
  const [items, setItems] = useState<CustomerQuestionCandidate[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const [customQuestion, setCustomQuestion] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [completed, setCompleted] = useState(0); const [submitted, setSubmitted] = useState(false); const [noticeWarning, setNoticeWarning] = useState('');
  useEffect(() => { mvpChatApi.listCustomerQuestionCandidates(caseId).then((next) => { setItems(next); setSelected(next.filter((item) => item.priority === 'P0').map((item) => item.question_id)); }).catch((reason) => setError(reason instanceof Error ? reason.message : '질문 후보를 불러오지 못했습니다.')).finally(() => setLoading(false)); }, [caseId]);
  const addCustom = () => { const text = customQuestion.trim(); if (!text) return; const id = `custom-${Date.now()}`; setItems((current) => [...current, { question_id: id, target_field: id, question_text: text, reason: '은행 직원이 직접 추가한 확인 질문입니다.', customer_explanation: '현재 상황에 맞는 다음 안내를 위해 은행 담당자가 확인하는 질문입니다.', priority: 'P1', options: [], answer_mode: 'TEXT', allow_free_text: true }]); setSelected((current) => [...current, id]); setCustomQuestion(''); };
  const queue = async () => {
    const questions = items.filter((item) => selected.includes(item.question_id));
    if (!questions.length) return;
    setSaving(true); setError(''); setNoticeWarning('');
    try {
      const created = await mvpChatApi.queueCustomerQuestions(caseId, questions, requestedBy);
      setCompleted(created.length); setSubmitted(true);
      try { if (created.length > 0) await mvpChatApi.createMessage(caseId, { actor_type: 'BANK_AGENT', actor_user_id: 'case-copilot', actor_display_name: 'CaseCopilot', actor_role: null, content: `고객 확인 질문 ${created.length}개가 전달되었습니다. 고객 답변을 기다리고 있습니다.`, channel: 'TEAM', audience: 'BANK_INTERNAL', visibility: 'BANK_INTERNAL', message_kind: 'SYSTEM_EVENT' }); }
      catch { setNoticeWarning('질문은 전달됐지만 은행 협업 알림을 동기화하지 못했습니다. 다시 실행하지 말고 새로고침해 주세요.'); }
      try { await onQueued(); } catch { setNoticeWarning('질문은 전달됐지만 최신 화면을 불러오지 못했습니다. 새로고침해 주세요.'); }
    } catch (reason) { setError(reason instanceof Error ? reason.message : '질문 대기열을 만들지 못했습니다.'); }
    finally { setSaving(false); }
  };
  return <section className="rounded-2xl border border-violet-400/50 bg-slate-950 p-4 text-slate-100 shadow-lg"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-black tracking-wide text-violet-300">AI 개인 작업 · 질문 추천</p><h2 className="mt-1 font-black">고객 확인 질문 후보</h2><p className="mt-1 text-xs leading-5 text-slate-400">선택한 질문만 고객 질문 대기열에 등록되고, 고객에게는 내부 사유 대신 맞춤 설명과 선택지가 표시됩니다.</p></div><button type="button" onClick={onClose} className="rounded-lg p-1 text-slate-400 hover:bg-slate-800" aria-label="질문 추천 카드 닫기"><X size={17}/></button></div>{loading ? <div className="grid min-h-24 place-items-center text-sm text-slate-400"><Loader2 className="mr-2 animate-spin" size={17}/>후보를 정리하는 중입니다.</div> : error ? <p className="mt-3 rounded-xl bg-rose-950/60 p-3 text-xs text-rose-200">{error}</p> : <div className="mt-4 space-y-2">{items.length ? items.map((item) => <label key={item.question_id} className="flex cursor-pointer gap-3 rounded-xl border border-slate-700 bg-slate-900 p-3"><input type="checkbox" checked={selected.includes(item.question_id)} onChange={() => setSelected((current) => current.includes(item.question_id) ? current.filter((id) => id !== item.question_id) : [...current, item.question_id])} className="mt-1 h-4 w-4 accent-violet-500"/><span className="min-w-0"><b className="text-sm">{item.question_text}</b><span className="mt-1 block text-[11px] text-slate-400">{item.reason}</span>{item.options?.length ? <span className="mt-2 flex flex-wrap gap-1">{item.options.map((option) => <span key={option} className="rounded-full bg-slate-800 px-2 py-1 text-[10px] font-bold text-slate-300">{option}</span>)}</span> : <span className="mt-2 block text-[10px] font-bold text-slate-500">고객 직접 입력형</span>}</span></label>) : <p className="rounded-xl bg-emerald-950/40 p-3 text-xs text-emerald-200">추가 질문 후보가 없습니다.</p>}</div>}
    <div className="mt-4 flex gap-2"><input value={customQuestion} onChange={(event) => setCustomQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { event.preventDefault(); addCustom(); } }} placeholder="직접 질문을 입력하세요" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-xs text-white"/><button type="button" onClick={addCustom} disabled={!customQuestion.trim()} className="inline-flex items-center gap-1 rounded-xl border border-violet-400/60 px-3 py-2 text-xs font-bold text-violet-200 disabled:opacity-40"><Plus size={14}/>질문 추가</button></div>{submitted && <p className="mt-3 rounded-xl border border-emerald-400/40 bg-emerald-950/50 p-3 text-xs font-bold text-emerald-200">{completed > 0 ? `실행 완료 · ${completed}개 질문이 고객 채널 대기열에 등록되었습니다.` : '선택한 질문은 이미 대기열에 등록되어 있습니다.'}</p>}{noticeWarning && <p className="mt-3 rounded-xl bg-amber-950/60 p-3 text-xs text-amber-200">{noticeWarning}</p>}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-slate-700 px-3 py-2 text-xs font-bold text-slate-300">닫기</button><button type="button" disabled={!selected.length || saving || submitted} onClick={() => void queue()} className="inline-flex items-center gap-1 rounded-xl bg-violet-500 px-3 py-2 text-xs font-black text-white disabled:opacity-50"><CheckSquare size={14}/>{saving ? '저장 중' : submitted ? '고객 질문으로 전달됨' : `${selected.length}개 질문 실행`}</button></div></section>;
};
