-- GENERATED by backend/scripts/build_schema_bootstrap.py --write
-- Source of truth: backend/migrations/manifest.json (global filename order).
-- EMPTY DATABASE ONLY. Existing databases must use apply_migrations.py.
-- Includes the explicit 023 demo staff seed, but no Case/customer/chat data.
-- MySQL batch/Docker initialization stops on a nonempty database; never use --force.
SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET @csr_init_guard_sql = IF(
  (SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE())=0,
  'DO 0',
  'SELECT * FROM information_schema.CSR_INIT_REQUIRES_EMPTY_DATABASE'
);
PREPARE csr_init_guard FROM @csr_init_guard_sql;
EXECUTE csr_init_guard;
DEALLOCATE PREPARE csr_init_guard;

CREATE TABLE schema_migrations (
    migration_name VARCHAR(255) PRIMARY KEY,
    applied_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);


-- Migration: 001_core_case_diagnosis.sql
CREATE TABLE IF NOT EXISTS cases (
    case_id VARCHAR(32) PRIMARY KEY,
    client_request_id VARCHAR(100) NULL UNIQUE,
    risk_level ENUM('NORMAL', 'LOW', 'HIGH') NOT NULL,
    risk_score DECIMAL(6, 3) NOT NULL,
    mode ENUM('PREVENT', 'RECOVERY', 'CLOSED') NOT NULL DEFAULT 'PREVENT',
    status ENUM('NEW', 'TRIAGE', 'VERIFYING', 'IN_PROGRESS', 'CLOSED') NOT NULL DEFAULT 'TRIAGE',
    initial_brief TEXT NOT NULL,
    diagnosis_json JSON NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS case_inputs (
    input_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    input_type ENUM('TEXT', 'VOICE_TRANSCRIPT') NOT NULL DEFAULT 'TEXT',
    input_text TEXT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    CONSTRAINT fk_case_inputs_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS analysis_segments (
    segment_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    start_turn INT NOT NULL,
    end_turn INT NOT NULL,
    segment_text TEXT NOT NULL,
    risk_score DECIMAL(6, 3) NOT NULL,
    model_label ENUM('NORMAL', 'PHISHING') NOT NULL,
    evidence_json JSON NOT NULL,
    created_at DATETIME(6) NOT NULL,
    CONSTRAINT fk_segments_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS context_features (
    feature_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    segment_id VARCHAR(64) NULL,
    feature_key VARCHAR(100) NOT NULL,
    feature_value DECIMAL(18, 6) NOT NULL,
    source VARCHAR(50) NOT NULL,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_context_features_case_key (case_id, feature_key),
    CONSTRAINT fk_features_case FOREIGN KEY (case_id) REFERENCES cases(case_id),
    CONSTRAINT fk_features_segment FOREIGN KEY (segment_id) REFERENCES analysis_segments(segment_id)
);

CREATE TABLE IF NOT EXISTS case_events (
    event_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json JSON NOT NULL,
    occurred_at DATETIME(6) NOT NULL,
    INDEX idx_case_events_case_cursor (case_id, event_id),
    CONSTRAINT fk_case_events_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('001_core_case_diagnosis.sql');


-- Migration: 002_initial_live_report.sql
CREATE TABLE IF NOT EXISTS case_reports (
    report_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    report_type ENUM('LIVE', 'FINAL') NOT NULL DEFAULT 'LIVE',
    report_version INT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    UNIQUE KEY uq_case_live_report (case_id, report_type),
    CONSTRAINT fk_case_reports_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS case_report_sections (
    report_id VARCHAR(64) NOT NULL,
    section_key VARCHAR(64) NOT NULL,
    content_json JSON NOT NULL,
    section_version INT NOT NULL DEFAULT 1,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (report_id, section_key),
    CONSTRAINT fk_report_sections_report FOREIGN KEY (report_id) REFERENCES case_reports(report_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('002_initial_live_report.sql');


-- Migration: 003_expand_risk_score_precision.sql
ALTER TABLE cases
    MODIFY risk_score DECIMAL(9, 6) NOT NULL;

ALTER TABLE analysis_segments
    MODIFY risk_score DECIMAL(9, 6) NOT NULL;

INSERT INTO schema_migrations (migration_name) VALUES ('003_expand_risk_score_precision.sql');


-- Migration: 004_case_messages_and_event_actor.sql
CREATE TABLE IF NOT EXISTS messages (
    message_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    client_request_id VARCHAR(100) NULL,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_messages_case_cursor (case_id, created_at, message_id),
    CONSTRAINT fk_messages_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

ALTER TABLE case_events
    ADD COLUMN actor_type VARCHAR(32) NOT NULL DEFAULT 'SYSTEM' AFTER event_type;

INSERT INTO schema_migrations (migration_name) VALUES ('004_case_messages_and_event_actor.sql');


-- Migration: 005_verification_actions.sql
CREATE TABLE IF NOT EXISTS verification_tasks (
    verification_task_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    claim TEXT NOT NULL,
    target VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    version INT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    INDEX idx_verification_tasks_case (case_id, created_at),
    CONSTRAINT fk_verification_tasks_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS actions (
    action_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    action_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'REQUESTED',
    actor_type VARCHAR(32) NOT NULL,
    note TEXT NOT NULL,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_actions_case_cursor (case_id, created_at, action_id),
    CONSTRAINT fk_actions_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('005_verification_actions.sql');


-- Migration: 006_case_version.sql
ALTER TABLE cases
    ADD COLUMN version INT NOT NULL DEFAULT 1 AFTER status;

INSERT INTO schema_migrations (migration_name) VALUES ('006_case_version.sql');


-- Migration: 007_voice_sessions.sql
CREATE TABLE IF NOT EXISTS voice_sessions (
    session_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    status ENUM('REQUESTED', 'ACTIVE', 'ENDED', 'FAILED') NOT NULL DEFAULT 'REQUESTED',
    participants_json JSON NOT NULL,
    started_at DATETIME(6) NULL,
    ended_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_voice_sessions_case (case_id, created_at),
    CONSTRAINT fk_voice_sessions_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS transcript_segments (
    segment_id VARCHAR(64) PRIMARY KEY,
    session_id VARCHAR(64) NOT NULL,
    case_id VARCHAR(32) NOT NULL,
    speaker VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    started_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_transcript_segments_session (session_id, created_at),
    CONSTRAINT fk_transcript_segments_session FOREIGN KEY (session_id) REFERENCES voice_sessions(session_id),
    CONSTRAINT fk_transcript_segments_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('007_voice_sessions.sql');


-- Migration: 008_collaboration_channels.sql
ALTER TABLE messages
    ADD COLUMN channel VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER' AFTER content,
    ADD COLUMN audience VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER' AFTER channel,
    ADD COLUMN mentions_json TEXT NULL AFTER audience,
    ADD COLUMN reply_to_message_id VARCHAR(64) NULL AFTER mentions_json;

UPDATE messages
SET mentions_json = '[]'
WHERE mentions_json IS NULL OR mentions_json = '';

CREATE TABLE IF NOT EXISTS case_members (
    case_id VARCHAR(32) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    role VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    assigned_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (case_id, user_id),
    CONSTRAINT fk_case_members_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS case_presence (
    case_id VARCHAR(32) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    presence VARCHAR(16) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    last_seen_at DATETIME(6) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    PRIMARY KEY (case_id, user_id),
    INDEX idx_case_presence_expiry (case_id, expires_at),
    CONSTRAINT fk_case_presence_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('008_collaboration_channels.sql');


-- Migration: 009_case_attachments.sql
CREATE TABLE IF NOT EXISTS case_attachments (
    attachment_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    original_name VARCHAR(160) NOT NULL,
    stored_name VARCHAR(80) NOT NULL,
    storage_path VARCHAR(512) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    sha256 CHAR(64) NOT NULL,
    uploaded_by VARCHAR(80) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'UPLOADED',
    visibility VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER',
    ai_readable BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_case_attachments_case_created (case_id, created_at, attachment_id),
    INDEX idx_case_attachments_sha256 (sha256),
    CONSTRAINT fk_case_attachments_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS message_attachments (
    message_id VARCHAR(64) NOT NULL,
    attachment_id VARCHAR(64) NOT NULL,
    attached_at DATETIME(6) NOT NULL,
    PRIMARY KEY (message_id, attachment_id),
    CONSTRAINT fk_message_attachments_message FOREIGN KEY (message_id) REFERENCES messages(message_id),
    CONSTRAINT fk_message_attachments_attachment FOREIGN KEY (attachment_id) REFERENCES case_attachments(attachment_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('009_case_attachments.sql');


-- Migration: 009_mysql_parity_workflow.sql
-- MySQL parity additions for the current Repository/Public API.
-- Run after migrations 001-008.

ALTER TABLE cases
    ADD COLUMN victim_transfer_status VARCHAR(30) NULL,
    ADD COLUMN actual_loss_amount_krw BIGINT NULL,
    ADD COLUMN deleted_at DATETIME(6) NULL;

ALTER TABLE messages
    ADD COLUMN actor_user_id VARCHAR(64) NULL,
    ADD COLUMN actor_display_name VARCHAR(80) NULL,
    ADD COLUMN actor_role VARCHAR(64) NULL,
    ADD COLUMN visibility VARCHAR(32) NOT NULL DEFAULT 'CUSTOMER',
    ADD COLUMN message_kind VARCHAR(32) NOT NULL DEFAULT 'CHAT',
    ADD COLUMN private_owner_user_id VARCHAR(64) NULL,
    ADD COLUMN attachments_json JSON NULL;

ALTER TABLE verification_tasks
    ADD COLUMN result_summary TEXT NULL,
    ADD COLUMN evidence_url VARCHAR(2000) NULL,
    ADD COLUMN verified_by VARCHAR(80) NULL,
    ADD COLUMN rag_source VARCHAR(255) NULL,
    ADD COLUMN customer_visible BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS customer_questions (
    question_id VARCHAR(100) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    target_field VARCHAR(100) NOT NULL,
    question_text TEXT NOT NULL,
    reason TEXT NOT NULL,
    priority VARCHAR(2) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    sequence INT NOT NULL,
    requested_by VARCHAR(80) NULL,
    asked_at DATETIME(6) NULL,
    answered_at DATETIME(6) NULL,
    options_json JSON NOT NULL,
    question_message_id VARCHAR(64) NULL,
    answer_message_id VARCHAR(64) NULL,
    answer_text TEXT NULL,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_customer_questions_case (case_id, sequence),
    CONSTRAINT fk_customer_questions_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS case_facts (
    fact_id VARCHAR(100) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    value TEXT NOT NULL,
    source VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    evidence_message_id VARCHAR(64) NULL,
    confirmed_by VARCHAR(80) NULL,
    confirmed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    INDEX idx_case_facts_case (case_id, field_name),
    CONSTRAINT fk_case_facts_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS personal_notes (
    note_id VARCHAR(100) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    author_id VARCHAR(80) NOT NULL,
    content TEXT NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'PRIVATE_TO_AUTHOR',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    INDEX idx_personal_notes_author (case_id, author_id, updated_at),
    CONSTRAINT fk_personal_notes_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('009_mysql_parity_workflow.sql');


-- Migration: 010_case_fact_question_link.sql
-- Preserve the originating customer question for human-readable Fact review.
-- Run after migrations 001-009.

ALTER TABLE case_facts
    ADD COLUMN source_question_id VARCHAR(100) NULL,
    ADD INDEX idx_case_facts_question (case_id, source_question_id);

INSERT INTO schema_migrations (migration_name) VALUES ('010_case_fact_question_link.sql');


-- Migration: 011_message_idempotency.sql
ALTER TABLE messages
    ADD UNIQUE KEY uq_messages_case_client_request (case_id, client_request_id);

INSERT INTO schema_migrations (migration_name) VALUES ('011_message_idempotency.sql');


-- Migration: 012_context_items.sql
-- Additive foundation only; existing Case/Action/Fact records are untouched.
CREATE TABLE IF NOT EXISTS case_context_items (
    item_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    section VARCHAR(32) NOT NULL,
    semantic_key VARCHAR(160) COLLATE utf8mb4_bin NOT NULL,
    item_version BIGINT NOT NULL,
    state_json JSON NOT NULL,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_context_semantic (case_id, section, semantic_key),
    CONSTRAINT fk_context_item_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

CREATE TABLE IF NOT EXISTS case_context_item_history (
    history_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    item_id VARCHAR(64) NOT NULL,
    item_version BIGINT NOT NULL,
    operation VARCHAR(24) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    before_json JSON NULL,
    after_json JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_context_history_version (item_id, item_version),
    CONSTRAINT fk_context_history_item FOREIGN KEY (item_id) REFERENCES case_context_items(item_id)
);

INSERT INTO schema_migrations (migration_name) VALUES ('012_context_items.sql');


-- Migration: 013_context_projection_revision.sql
-- Durable semantic revision and single-flight projection state.
-- UI preferences, presence, bookmarks, private notes and context wording
-- overlays deliberately do not advance this revision.
ALTER TABLE cases
    ADD COLUMN context_revision BIGINT NOT NULL DEFAULT 1 AFTER version;

CREATE TABLE IF NOT EXISTS case_context_projections (
    case_id VARCHAR(32) PRIMARY KEY,
    generation_status VARCHAR(16) NOT NULL DEFAULT 'EMPTY',
    generating_revision BIGINT NULL,
    lease_token VARCHAR(64) NULL,
    lease_expires_at DATETIME(6) NULL,
    last_success_revision BIGINT NULL,
    last_success_payload JSON NULL,
    schema_version VARCHAR(32) NOT NULL DEFAULT 'case-support.v1',
    model_version VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    last_error VARCHAR(500) NULL,
    generated_at DATETIME(6) NULL,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_context_projection_case FOREIGN KEY (case_id) REFERENCES cases(case_id)
);

-- Direct changes to fields used by the Case Context projection.
CREATE TRIGGER trg_cases_context_revision_update
BEFORE UPDATE ON cases FOR EACH ROW
SET NEW.context_revision = GREATEST(
    NEW.context_revision,
    OLD.context_revision + IF(
        NOT (OLD.mode <=> NEW.mode)
        OR NOT (OLD.status <=> NEW.status)
        OR NOT (OLD.diagnosis_json <=> NEW.diagnosis_json)
        OR NOT (OLD.victim_transfer_status <=> NEW.victim_transfer_status)
        OR NOT (OLD.actual_loss_amount_krw <=> NEW.actual_loss_amount_krw),
        1, 0
    )
);

CREATE TRIGGER trg_messages_context_revision_insert
AFTER INSERT ON messages FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_messages_context_revision_delete
AFTER DELETE ON messages FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

CREATE TRIGGER trg_questions_context_revision_insert
AFTER INSERT ON customer_questions FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_questions_context_revision_update
AFTER UPDATE ON customer_questions FOR EACH ROW
UPDATE cases SET context_revision=context_revision + IF(
    NOT (OLD.target_field <=> NEW.target_field)
    OR NOT (OLD.question_text <=> NEW.question_text)
    OR NOT (OLD.reason <=> NEW.reason)
    OR NOT (OLD.priority <=> NEW.priority)
    OR NOT (OLD.status <=> NEW.status)
    OR NOT (OLD.answer_text <=> NEW.answer_text), 1, 0
) WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_questions_context_revision_delete
AFTER DELETE ON customer_questions FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

CREATE TRIGGER trg_facts_context_revision_insert
AFTER INSERT ON case_facts FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_facts_context_revision_update
AFTER UPDATE ON case_facts FOR EACH ROW
UPDATE cases SET context_revision=context_revision + IF(
    NOT (OLD.field_name <=> NEW.field_name)
    OR NOT (OLD.value <=> NEW.value)
    OR NOT (OLD.source <=> NEW.source)
    OR NOT (OLD.status <=> NEW.status), 1, 0
) WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_facts_context_revision_delete
AFTER DELETE ON case_facts FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

CREATE TRIGGER trg_verifications_context_revision_insert
AFTER INSERT ON verification_tasks FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_verifications_context_revision_update
AFTER UPDATE ON verification_tasks FOR EACH ROW
UPDATE cases SET context_revision=context_revision + IF(
    NOT (OLD.claim <=> NEW.claim)
    OR NOT (OLD.target <=> NEW.target)
    OR NOT (OLD.status <=> NEW.status)
    OR NOT (OLD.result_summary <=> NEW.result_summary), 1, 0
) WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_verifications_context_revision_delete
AFTER DELETE ON verification_tasks FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

CREATE TRIGGER trg_actions_context_revision_insert
AFTER INSERT ON actions FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_actions_context_revision_update
AFTER UPDATE ON actions FOR EACH ROW
UPDATE cases SET context_revision=context_revision + IF(
    NOT (OLD.action_type <=> NEW.action_type)
    OR NOT (OLD.status <=> NEW.status)
    OR NOT (OLD.note <=> NEW.note), 1, 0
) WHERE case_id=NEW.case_id;

CREATE TRIGGER trg_actions_context_revision_delete
AFTER DELETE ON actions FOR EACH ROW
UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

INSERT INTO schema_migrations (migration_name) VALUES ('013_context_projection_revision.sql');


-- Migration: 014_case_context_v2_foundation.sql
-- Additive Case Context v2 storage foundation.
-- No existing table is renamed, rewritten, or dropped by this migration.

CREATE TABLE IF NOT EXISTS case_context_facts_v2 (
    fact_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    semantic_key VARCHAR(160) COLLATE utf8mb4_bin NOT NULL,
    display_label VARCHAR(255) NOT NULL,
    value_json JSON NOT NULL,
    display_value TEXT NOT NULL,
    source_kind VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PROPOSED',
    confidence DECIMAL(5,4) NULL,
    evidence_refs_json JSON NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'BANK_INTERNAL',
    confirmed_by VARCHAR(64) NULL,
    confirmed_at DATETIME(6) NULL,
    rejection_reason VARCHAR(1000) NULL,
    supersedes_fact_id VARCHAR(64) NULL,
    client_request_id VARCHAR(100) NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_context_fact_request (case_id, client_request_id),
    INDEX idx_context_facts_case_state (case_id, status, semantic_key),
    CONSTRAINT fk_context_fact_v2_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT fk_context_fact_v2_supersedes FOREIGN KEY (supersedes_fact_id) REFERENCES case_context_facts_v2(fact_id) ON DELETE SET NULL,
    CONSTRAINT chk_context_fact_status CHECK (status IN ('PROPOSED','CONFIRMED','REJECTED','SUPERSEDED')),
    CONSTRAINT chk_context_fact_source CHECK (source_kind IN ('AI_EXTRACTION','CUSTOMER_STATEMENT','STAFF_OBSERVATION','BANK_RECORD','OFFICIAL_VERIFICATION')),
    CONSTRAINT chk_context_fact_visibility CHECK (visibility IN ('BANK_INTERNAL','CUSTOMER_SHARED')),
    CONSTRAINT chk_context_fact_confidence CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
    CONSTRAINT chk_context_fact_confirmed CHECK (status <> 'CONFIRMED' OR (confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL)),
    CONSTRAINT chk_context_fact_rejected CHECK (status <> 'REJECTED' OR rejection_reason IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS case_gaps (
    gap_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    semantic_key VARCHAR(160) COLLATE utf8mb4_bin NOT NULL,
    title VARCHAR(300) NOT NULL,
    reason TEXT NOT NULL,
    priority VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    source VARCHAR(24) NOT NULL,
    evidence_refs_json JSON NOT NULL,
    related_question_ids_json JSON NOT NULL,
    related_verification_ids_json JSON NOT NULL,
    resolution_fact_id VARCHAR(64) NULL,
    dismissal_reason VARCHAR(1000) NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'BANK_INTERNAL',
    source_revision BIGINT NOT NULL,
    client_request_id VARCHAR(100) NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    active_semantic_key VARCHAR(160) COLLATE utf8mb4_bin GENERATED ALWAYS AS (
        CASE WHEN status IN ('OPEN','AWAITING_CUSTOMER','AWAITING_INSTITUTION','STAFF_REVIEW_REQUIRED') THEN semantic_key ELSE NULL END
    ) STORED,
    UNIQUE KEY uq_case_gap_active (case_id, active_semantic_key),
    UNIQUE KEY uq_case_gap_request (case_id, client_request_id),
    INDEX idx_case_gaps_state (case_id, status, priority),
    CONSTRAINT fk_case_gap_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT fk_case_gap_resolution FOREIGN KEY (resolution_fact_id) REFERENCES case_context_facts_v2(fact_id) ON DELETE RESTRICT,
    CONSTRAINT chk_case_gap_status CHECK (status IN ('OPEN','AWAITING_CUSTOMER','AWAITING_INSTITUTION','STAFF_REVIEW_REQUIRED','RESOLVED','DISMISSED')),
    CONSTRAINT chk_case_gap_priority CHECK (priority IN ('URGENT','HIGH','NORMAL')),
    CONSTRAINT chk_case_gap_source CHECK (source IN ('AI','BANK_STAFF','SYSTEM_RULE')),
    CONSTRAINT chk_case_gap_visibility CHECK (visibility = 'BANK_INTERNAL'),
    CONSTRAINT chk_case_gap_resolved CHECK (status <> 'RESOLVED' OR resolution_fact_id IS NOT NULL),
    CONSTRAINT chk_case_gap_dismissed CHECK (status <> 'DISMISSED' OR dismissal_reason IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS case_ai_suggestions (
    suggestion_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    suggestion_type VARCHAR(40) NOT NULL,
    title VARCHAR(300) NOT NULL,
    rationale TEXT NOT NULL,
    priority VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PROPOSED',
    related_gap_ids_json JSON NOT NULL,
    evidence_refs_json JSON NOT NULL,
    dedupe_key VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,
    execution_mode VARCHAR(40) NOT NULL DEFAULT 'HUMAN_REVIEW_REQUIRED',
    source_revision BIGINT NOT NULL,
    model_version VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    accepted_task_id VARCHAR(64) NULL,
    reviewed_by VARCHAR(64) NULL,
    reviewed_at DATETIME(6) NULL,
    dismissal_reason VARCHAR(1000) NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    active_dedupe_key VARCHAR(255) COLLATE utf8mb4_bin GENERATED ALWAYS AS (
        CASE WHEN status = 'PROPOSED' THEN dedupe_key ELSE NULL END
    ) STORED,
    UNIQUE KEY uq_ai_suggestion_active (case_id, active_dedupe_key),
    INDEX idx_ai_suggestions_state (case_id, status, priority),
    CONSTRAINT fk_ai_suggestion_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT chk_ai_suggestion_type CHECK (suggestion_type IN ('CUSTOMER_QUESTION','INSTITUTION_VERIFICATION','TRANSACTION_REVIEW','PROTECTIVE_ACTION','DOCUMENT_REQUEST','STAFF_REVIEW')),
    CONSTRAINT chk_ai_suggestion_priority CHECK (priority IN ('URGENT','HIGH','NORMAL')),
    CONSTRAINT chk_ai_suggestion_status CHECK (status IN ('PROPOSED','ACCEPTED','DISMISSED','EXPIRED','SUPERSEDED')),
    CONSTRAINT chk_ai_suggestion_mode CHECK (execution_mode IN ('HUMAN_REVIEW_REQUIRED','AUTO_CUSTOMER_QUESTION_ALLOWED')),
    CONSTRAINT chk_ai_suggestion_review CHECK (status NOT IN ('ACCEPTED','DISMISSED') OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)),
    CONSTRAINT chk_ai_suggestion_dismissed CHECK (status <> 'DISMISSED' OR dismissal_reason IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS case_tasks (
    task_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    source VARCHAR(32) NOT NULL,
    source_suggestion_id VARCHAR(64) NULL,
    task_type VARCHAR(40) NOT NULL,
    title VARCHAR(300) NOT NULL,
    description TEXT NOT NULL,
    priority VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'TODO',
    assignee_user_id VARCHAR(64) NULL,
    due_at DATETIME(6) NULL,
    related_gap_ids_json JSON NOT NULL,
    related_verification_ids_json JSON NOT NULL,
    result_code VARCHAR(100) NULL,
    result_summary TEXT NULL,
    evidence_refs_json JSON NOT NULL,
    customer_visibility VARCHAR(32) NOT NULL DEFAULT 'INTERNAL_ONLY',
    completed_by VARCHAR(64) NULL,
    completed_at DATETIME(6) NULL,
    cancellation_reason VARCHAR(1000) NULL,
    client_request_id VARCHAR(100) NULL,
    version BIGINT NOT NULL DEFAULT 1,
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_case_task_request (case_id, client_request_id),
    INDEX idx_case_tasks_state (case_id, status, priority, updated_at),
    INDEX idx_case_tasks_assignee (case_id, assignee_user_id, status),
    CONSTRAINT fk_case_task_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT fk_case_task_suggestion FOREIGN KEY (source_suggestion_id) REFERENCES case_ai_suggestions(suggestion_id) ON DELETE SET NULL,
    CONSTRAINT chk_case_task_source CHECK (source IN ('STAFF_CREATED','AI_SUGGESTION_ACCEPTED','SYSTEM_REQUIRED')),
    CONSTRAINT chk_case_task_type CHECK (task_type IN ('CUSTOMER_CONTACT','INSTITUTION_VERIFICATION','TRANSACTION_REVIEW','PROTECTIVE_ACTION','DOCUMENT_REVIEW','OTHER')),
    CONSTRAINT chk_case_task_priority CHECK (priority IN ('URGENT','HIGH','NORMAL')),
    CONSTRAINT chk_case_task_status CHECK (status IN ('TODO','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED')),
    CONSTRAINT chk_case_task_visibility CHECK (customer_visibility IN ('INTERNAL_ONLY','RESULT_SHAREABLE','RESULT_PUBLISHED')),
    CONSTRAINT chk_case_task_completed CHECK (status <> 'COMPLETED' OR (result_summary IS NOT NULL AND completed_by IS NOT NULL AND completed_at IS NOT NULL)),
    CONSTRAINT chk_case_task_cancelled CHECK (status <> 'CANCELLED' OR cancellation_reason IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS case_decisions (
    decision_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    decision_type VARCHAR(32) NOT NULL,
    title VARCHAR(300) NOT NULL,
    rationale TEXT NOT NULL,
    related_entity_type VARCHAR(24) NOT NULL,
    related_entity_id VARCHAR(100) NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'BANK_INTERNAL',
    actor_user_id VARCHAR(64) NOT NULL,
    supersedes_decision_id VARCHAR(64) NULL,
    client_request_id VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_case_decision_request (case_id, client_request_id),
    INDEX idx_case_decisions_created (case_id, created_at, decision_id),
    CONSTRAINT fk_case_decision_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT fk_case_decision_supersedes FOREIGN KEY (supersedes_decision_id) REFERENCES case_decisions(decision_id) ON DELETE SET NULL,
    CONSTRAINT chk_case_decision_type CHECK (decision_type IN ('FACT_REVIEW','TASK_DECISION','CASE_STATUS','CUSTOMER_DISCLOSURE','OTHER')),
    CONSTRAINT chk_case_decision_entity CHECK (related_entity_type IN ('FACT','GAP','SUGGESTION','TASK','VERIFICATION','CASE')),
    CONSTRAINT chk_case_decision_visibility CHECK (visibility IN ('BANK_INTERNAL','CUSTOMER_SHARED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS case_context_v2_history (
    history_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    entity_type VARCHAR(24) NOT NULL,
    entity_id VARCHAR(64) NOT NULL,
    entity_version BIGINT NOT NULL,
    operation VARCHAR(32) NOT NULL,
    actor_user_id VARCHAR(64) NOT NULL,
    before_json JSON NULL,
    after_json JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY uq_context_v2_history_version (entity_type, entity_id, entity_version),
    INDEX idx_context_v2_history_case (case_id, created_at),
    CONSTRAINT fk_context_v2_history_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TRIGGER IF EXISTS trg_context_facts_v2_insert;
CREATE TRIGGER trg_context_facts_v2_insert AFTER INSERT ON case_context_facts_v2 FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_context_facts_v2_update;
CREATE TRIGGER trg_context_facts_v2_update AFTER UPDATE ON case_context_facts_v2 FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_context_facts_v2_delete;
CREATE TRIGGER trg_context_facts_v2_delete AFTER DELETE ON case_context_facts_v2 FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

DROP TRIGGER IF EXISTS trg_case_gaps_insert;
CREATE TRIGGER trg_case_gaps_insert AFTER INSERT ON case_gaps FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_case_gaps_update;
CREATE TRIGGER trg_case_gaps_update AFTER UPDATE ON case_gaps FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_case_gaps_delete;
CREATE TRIGGER trg_case_gaps_delete AFTER DELETE ON case_gaps FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

DROP TRIGGER IF EXISTS trg_ai_suggestions_insert;
CREATE TRIGGER trg_ai_suggestions_insert AFTER INSERT ON case_ai_suggestions FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_ai_suggestions_update;
CREATE TRIGGER trg_ai_suggestions_update AFTER UPDATE ON case_ai_suggestions FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_ai_suggestions_delete;
CREATE TRIGGER trg_ai_suggestions_delete AFTER DELETE ON case_ai_suggestions FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

DROP TRIGGER IF EXISTS trg_case_tasks_insert;
CREATE TRIGGER trg_case_tasks_insert AFTER INSERT ON case_tasks FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_case_tasks_update;
CREATE TRIGGER trg_case_tasks_update AFTER UPDATE ON case_tasks FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_case_tasks_delete;
CREATE TRIGGER trg_case_tasks_delete AFTER DELETE ON case_tasks FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

DROP TRIGGER IF EXISTS trg_case_decisions_insert;
CREATE TRIGGER trg_case_decisions_insert AFTER INSERT ON case_decisions FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=NEW.case_id;
DROP TRIGGER IF EXISTS trg_case_decisions_delete;
CREATE TRIGGER trg_case_decisions_delete AFTER DELETE ON case_decisions FOR EACH ROW UPDATE cases SET context_revision=context_revision+1 WHERE case_id=OLD.case_id;

INSERT INTO schema_migrations (migration_name) VALUES ('014_case_context_v2_foundation.sql');


-- Migration: 015_context_panel_v3.sql
-- Context Panel V3 additive persistence. Existing messages/facts/questions are retained.

ALTER TABLE customer_questions
    ADD COLUMN allow_multi_select BOOLEAN NOT NULL DEFAULT FALSE AFTER options_json,
    ADD COLUMN question_version BIGINT NOT NULL DEFAULT 1 AFTER answer_text,
    ADD COLUMN answer_payload_json JSON NULL AFTER question_version,
    ADD COLUMN answer_question_version BIGINT NULL AFTER answer_payload_json;

CREATE TABLE IF NOT EXISTS message_context_extractions (
    extraction_id VARCHAR(64) PRIMARY KEY,
    case_id VARCHAR(32) NOT NULL,
    message_id VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    last_error VARCHAR(1000) NULL,
    model_version VARCHAR(100) NULL,
    prompt_version VARCHAR(100) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at DATETIME(6) NULL,
    UNIQUE KEY uq_message_context_extraction_message (message_id),
    INDEX idx_message_context_extraction_retry (status, attempts, updated_at),
    INDEX idx_message_context_extraction_case (case_id, created_at),
    CONSTRAINT fk_message_context_extraction_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT fk_message_context_extraction_message FOREIGN KEY (message_id) REFERENCES messages(message_id) ON DELETE CASCADE,
    CONSTRAINT chk_message_context_extraction_status CHECK (status IN ('PENDING','PROCESSING','COMPLETED','FAILED','SKIPPED')),
    CONSTRAINT chk_message_context_extraction_attempts CHECK (attempts BETWEEN 0 AND 3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TRIGGER IF EXISTS trg_questions_context_revision_update;
CREATE TRIGGER trg_questions_context_revision_update AFTER UPDATE ON customer_questions FOR EACH ROW
UPDATE cases SET context_revision=context_revision+IF(
    NOT (OLD.target_field <=> NEW.target_field) OR NOT (OLD.question_text <=> NEW.question_text)
    OR NOT (OLD.reason <=> NEW.reason) OR NOT (OLD.priority <=> NEW.priority)
    OR NOT (OLD.status <=> NEW.status) OR NOT (OLD.answer_text <=> NEW.answer_text)
    OR NOT (OLD.answer_payload_json <=> NEW.answer_payload_json), 1, 0
) WHERE case_id=NEW.case_id;

INSERT INTO schema_migrations (migration_name) VALUES ('015_context_panel_v3.sql');


-- Migration: 016_case_name.sql
-- Staff-editable display name for the Case list and Case room.

ALTER TABLE cases
    ADD COLUMN case_name VARCHAR(200) NULL AFTER case_id;

INSERT INTO schema_migrations (migration_name) VALUES ('016_case_name.sql');


-- Migration: 017_structured_context_resources.sql
-- Durable, privacy-safe storage for the A-part structured diagnosis result.
-- Raw call text is never copied into these tables.

CREATE TABLE IF NOT EXISTS case_semantic_atoms (
    case_id VARCHAR(32) NOT NULL,
    atom_id VARCHAR(80) NOT NULL,
    atom_class VARCHAR(80) NOT NULL,
    predicate VARCHAR(120) NOT NULL,
    source_turn_id INT NOT NULL,
    semantic_fingerprint VARCHAR(128) NOT NULL,
    payload_json JSON NOT NULL,
    source_revision BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (case_id, atom_id),
    UNIQUE KEY uq_case_atom_fingerprint (case_id, semantic_fingerprint),
    INDEX idx_case_atoms_turn (case_id, source_turn_id),
    CONSTRAINT fk_case_atoms_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS case_semantic_relations (
    case_id VARCHAR(32) NOT NULL,
    relation_id VARCHAR(100) NOT NULL,
    relation_type VARCHAR(32) NOT NULL,
    source_atom_id VARCHAR(80) NOT NULL,
    target_atom_id VARCHAR(80) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    payload_json JSON NOT NULL,
    source_revision BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (case_id, relation_id),
    INDEX idx_case_relations_atoms (case_id, source_atom_id, target_atom_id),
    CONSTRAINT fk_case_relations_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT chk_case_relation_confidence CHECK (confidence >= 0 AND confidence <= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS case_context_signals (
    case_id VARCHAR(32) NOT NULL,
    signal_id VARCHAR(100) NOT NULL,
    signal_code VARCHAR(120) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    claim_status VARCHAR(32) NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'BANK_INTERNAL',
    payload_json JSON NOT NULL,
    source_revision BIGINT NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (case_id, signal_id),
    INDEX idx_case_signals_state (case_id, severity, visibility),
    CONSTRAINT fk_case_signals_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT chk_case_signal_confidence CHECK (confidence >= 0 AND confidence <= 1),
    CONSTRAINT chk_case_signal_visibility CHECK (visibility IN ('BANK_INTERNAL', 'CUSTOMER_SHARED', 'SHARED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (migration_name) VALUES ('017_structured_context_resources.sql');


-- Migration: 018_action_contract_fields.sql
-- Additive Action contract expansion for the shared migration sequence.
-- Existing Action rows and note content are retained; note remains the
-- compatibility description field. Apply only after migrations 001-017.

ALTER TABLE actions
    ADD COLUMN title VARCHAR(300) NULL AFTER action_type,
    ADD COLUMN version BIGINT NOT NULL DEFAULT 1 AFTER actor_type,
    ADD COLUMN updated_at DATETIME(6) NULL AFTER created_at,
    ADD COLUMN updated_by VARCHAR(128) NULL AFTER updated_at,
    ADD COLUMN visibility VARCHAR(32) NOT NULL DEFAULT 'BANK_INTERNAL' AFTER updated_by;

-- Historical rows have no independent modification timestamp. Preserve their
-- known creation timestamp rather than assigning migration execution time.
UPDATE actions
SET updated_at = created_at
WHERE updated_at IS NULL;

ALTER TABLE actions
    MODIFY COLUMN updated_at DATETIME(6) NOT NULL,
    ADD CONSTRAINT chk_actions_version CHECK (version >= 1),
    ADD CONSTRAINT chk_actions_visibility CHECK (visibility IN ('BANK_INTERNAL', 'CUSTOMER_SHARED'));

INSERT INTO schema_migrations (migration_name) VALUES ('018_action_contract_fields.sql');


-- Migration: 019_context_observations.sql
-- Open-world extension storage for privacy-safe observations not yet mapped to a Fact.
-- Additive only: existing Context v2 tables and contracts remain unchanged.
CREATE TABLE IF NOT EXISTS case_context_observations (
    observation_id VARCHAR(100) NOT NULL,
    case_id VARCHAR(32) NOT NULL,
    observation_type VARCHAR(80) NOT NULL,
    payload_json JSON NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'UNMAPPED',
    created_by VARCHAR(64) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (case_id, observation_id),
    INDEX idx_context_observations_review (case_id, status, created_at),
    CONSTRAINT fk_context_observations_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE,
    CONSTRAINT chk_context_observations_status CHECK (status IN ('UNMAPPED','REVIEWED','MAPPED','DISMISSED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (migration_name) VALUES ('019_context_observations.sql');


-- Migration: 020_bank_staff_directory.sql
CREATE TABLE IF NOT EXISTS bank_staff_directory (
    staff_id VARCHAR(64) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    assignment_role VARCHAR(32) NOT NULL DEFAULT 'CONSULTATION',
    role_label VARCHAR(100) NOT NULL,
    position_title VARCHAR(100) NULL,
    status_text VARCHAR(80) NOT NULL DEFAULT '근무 중',
    status_color_key VARCHAR(16) NOT NULL DEFAULT 'GREEN',
    assignment_eligible BOOLEAN NOT NULL DEFAULT TRUE,
    linked_user_id VARCHAR(64) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (staff_id),
    INDEX idx_bank_staff_active (deleted_at, display_name),
    CONSTRAINT chk_bank_staff_assignment_role CHECK (assignment_role IN ('SUPERVISOR','MONITORING','CONSULTATION','OTHER_VIEWER','HANDOVER_PENDING')),
    CONSTRAINT chk_bank_staff_color CHECK (status_color_key IN ('GREEN','BLUE','YELLOW','ORANGE','RED','PURPLE','GRAY'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (migration_name) VALUES ('020_bank_staff_directory.sql');


-- Migration: 021_create_case_transactions.sql
CREATE TABLE IF NOT EXISTS case_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  case_id VARCHAR(32) NOT NULL,
  transaction_type VARCHAR(32) NOT NULL,
  transaction_at DATETIME(6) NOT NULL,
  amount DECIMAL(19,2) NOT NULL,
  account_number VARCHAR(100) NULL,
  counterparty_name VARCHAR(100) NULL,
  counterparty_account VARCHAR(100) NULL,
  bank_name VARCHAR(100) NULL,
  memo VARCHAR(500) NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (id),
  KEY idx_case_transactions_case_at (case_id, transaction_at),
  CONSTRAINT fk_case_transactions_case FOREIGN KEY (case_id) REFERENCES cases(case_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (migration_name) VALUES ('021_create_case_transactions.sql');


-- Migration: 022_case_member_assignment_roles.sql
ALTER TABLE case_members
    ADD COLUMN assignment_role VARCHAR(32) NOT NULL DEFAULT 'HANDOVER_PENDING' AFTER role,
    ADD CONSTRAINT chk_case_member_assignment_role CHECK (assignment_role IN ('SUPERVISOR','MONITORING','CONSULTATION','VIEWER','HANDOVER_PENDING'));

INSERT INTO schema_migrations (migration_name) VALUES ('022_case_member_assignment_roles.sql');


-- Migration: 023_bank_staff_demo_seed.sql
-- 기본 화면 확인을 위한 은행 담당자 목데이터.
-- 동일한 staff_id를 사용해 마이그레이션을 여러 번 실행해도 중복 생성하지 않는다.
INSERT IGNORE INTO bank_staff_directory (
    staff_id,
    display_name,
    assignment_role,
    role_label,
    position_title,
    status_text,
    status_color_key,
    assignment_eligible,
    linked_user_id
) VALUES
    (
        'staff-demo-hong-gildong',
        '홍길동',
        'MONITORING',
        'FDS 모니터링 담당자',
        '대리',
        '근무 중',
        'GREEN',
        TRUE,
        NULL
    ),
    (
        'staff-demo-kim-cheolsu',
        '김철수',
        'CONSULTATION',
        '상담자',
        '주임',
        '근무 중',
        'GREEN',
        TRUE,
        NULL
    );

INSERT INTO schema_migrations (migration_name) VALUES ('023_bank_staff_demo_seed.sql');


-- Migration: 024_bank_staff_role_schema_alignment.sql
-- Align historical 021 staff-role installations with the current 020 contract.
-- Widen only; no role reassignment, seed overwrite or business-row deletion.
ALTER TABLE bank_staff_directory
    MODIFY COLUMN assignment_role VARCHAR(32) NOT NULL DEFAULT 'CONSULTATION',
    DROP CHECK chk_bank_staff_assignment_role,
    ADD CONSTRAINT chk_bank_staff_assignment_role CHECK (
        assignment_role IN ('SUPERVISOR','MONITORING','CONSULTATION','OTHER_VIEWER','HANDOVER_PENDING')
    );

INSERT INTO schema_migrations (migration_name) VALUES ('024_bank_staff_role_schema_alignment.sql');


-- Migration: 025_retire_transcript_storage.sql
-- Retire the legacy raw transcript table.
-- This migration is deliberately fail-closed: it drops the table only when
-- it is empty. Any existing transcript data blocks the migration for manual
-- review instead of being deleted implicitly.
SET @csr_transcript_table_exists = (
    SELECT COUNT(*)
    FROM information_schema.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'transcript_segments'
);
SET @csr_transcript_rows = IF(
    @csr_transcript_table_exists = 1,
    (SELECT COUNT(*) FROM transcript_segments),
    0
);
SET @csr_retire_transcript_sql = IF(
    @csr_transcript_table_exists = 0,
    'SELECT 1',
    IF(
        @csr_transcript_rows = 0,
        'DROP TABLE transcript_segments',
        'SELECT * FROM information_schema.CSR_TRANSCRIPT_RETIRE_BLOCKED'
    )
);
PREPARE csr_retire_transcript FROM @csr_retire_transcript_sql;
EXECUTE csr_retire_transcript;
DEALLOCATE PREPARE csr_retire_transcript;

INSERT INTO schema_migrations (migration_name) VALUES ('025_retire_transcript_storage.sql');


-- Migration: 026_retire_attachments.sql
-- Retire the demo-only attachment tables.
-- Fail closed: existing rows block the migration so data cannot be deleted implicitly.
SET @csr_case_attachment_table_exists = (
    SELECT COUNT(*) FROM information_schema.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'case_attachments'
);
SET @csr_message_attachment_table_exists = (
    SELECT COUNT(*) FROM information_schema.TABLES
    WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'message_attachments'
);
SET @csr_case_attachment_rows = IF(
    @csr_case_attachment_table_exists = 1,
    (SELECT COUNT(*) FROM case_attachments),
    0
);
SET @csr_message_attachment_rows = IF(
    @csr_message_attachment_table_exists = 1,
    (SELECT COUNT(*) FROM message_attachments),
    0
);
SET @csr_retire_attachment_sql = IF(
    @csr_case_attachment_rows = 0 AND @csr_message_attachment_rows = 0,
    'DROP TABLE IF EXISTS message_attachments, case_attachments',
    'SELECT * FROM information_schema.CSR_ATTACHMENT_RETIRE_BLOCKED'
);
PREPARE csr_retire_attachments FROM @csr_retire_attachment_sql;
EXECUTE csr_retire_attachments;
DEALLOCATE PREPARE csr_retire_attachments;

INSERT INTO schema_migrations (migration_name) VALUES ('026_retire_attachments.sql');


-- Migration: 027_migrate_legacy_case_facts_to_v2.sql
-- Copy the two explicitly supported legacy fact fields into the V2 authority.
-- This migration is idempotent through the deterministic client_request_id.
-- No legacy rows are deleted here; 028 performs the guarded retirement.

INSERT INTO case_context_facts_v2 (
    fact_id, case_id, semantic_key, display_label, value_json, display_value,
    source_kind, status, confidence, evidence_refs_json, visibility,
    confirmed_by, confirmed_at, client_request_id, version, created_at, updated_at
)
SELECT
    CONCAT('legacy-', LEFT(SHA2(CONCAT(cf.case_id, ':', cf.fact_id), 256), 57)),
    cf.case_id,
    CASE cf.field_name
        WHEN 'authentication_information_exposure' THEN 'exposure.authentication_information'
        WHEN 'personal_information_exposure' THEN 'exposure.personal_information'
    END,
    CASE cf.field_name
        WHEN 'authentication_information_exposure' THEN '인증정보 노출 여부'
        WHEN 'personal_information_exposure' THEN '개인정보 노출 여부'
    END,
    JSON_OBJECT('legacy_value', cf.value, 'legacy_field', cf.field_name),
    cf.value,
    CASE cf.source
        WHEN 'AI_EXTRACTED' THEN 'AI_EXTRACTION'
        WHEN 'HUMAN_CONFIRMED' THEN 'STAFF_OBSERVATION'
        WHEN 'VERIFIED' THEN 'OFFICIAL_VERIFICATION'
        WHEN 'UNRESOLVED' THEN 'STAFF_OBSERVATION'
    END,
    CASE cf.status WHEN 'CONFIRMED' THEN 'CONFIRMED' ELSE 'PROPOSED' END,
    cf.confidence,
    CASE
        WHEN cf.evidence_message_id IS NOT NULL AND cf.source_question_id IS NOT NULL THEN JSON_ARRAY(
            JSON_OBJECT('type', 'MESSAGE', 'id', cf.evidence_message_id),
            JSON_OBJECT('type', 'QUESTION_ANSWER', 'id', cf.source_question_id)
        )
        WHEN cf.evidence_message_id IS NOT NULL THEN JSON_ARRAY(JSON_OBJECT('type', 'MESSAGE', 'id', cf.evidence_message_id))
        WHEN cf.source_question_id IS NOT NULL THEN JSON_ARRAY(JSON_OBJECT('type', 'QUESTION_ANSWER', 'id', cf.source_question_id))
        ELSE JSON_ARRAY()
    END,
    'BANK_INTERNAL',
    CASE WHEN cf.status = 'CONFIRMED' THEN cf.confirmed_by ELSE NULL END,
    CASE WHEN cf.status = 'CONFIRMED' THEN cf.confirmed_at ELSE NULL END,
    CONCAT('legacy-case-fact:', cf.fact_id),
    1,
    cf.created_at,
    cf.created_at
FROM case_facts cf
WHERE cf.field_name IN ('authentication_information_exposure', 'personal_information_exposure')
  AND cf.source IN ('AI_EXTRACTED', 'HUMAN_CONFIRMED', 'VERIFIED', 'UNRESOLVED')
ON DUPLICATE KEY UPDATE fact_id = VALUES(fact_id);

INSERT INTO schema_migrations (migration_name) VALUES ('027_migrate_legacy_case_facts_to_v2.sql');


-- Migration: 028_retire_legacy_case_facts.sql
-- Retire the legacy table after every supported row has a V2 copy.

DELETE cf
FROM case_facts cf
LEFT JOIN case_context_facts_v2 v2
  ON v2.client_request_id = CONCAT('legacy-case-fact:', cf.fact_id)
WHERE v2.fact_id IS NOT NULL;

SET @remaining_legacy_case_facts = (SELECT COUNT(*) FROM case_facts);
SET @retire_case_facts_sql = IF(
    @remaining_legacy_case_facts = 0,
    'DROP TABLE case_facts',
    'THIS IS INTENTIONALLY INVALID SQL: unsupported legacy case_facts rows remain'
);
PREPARE retire_case_facts_stmt FROM @retire_case_facts_sql;
EXECUTE retire_case_facts_stmt;
DEALLOCATE PREPARE retire_case_facts_stmt;

INSERT INTO schema_migrations (migration_name) VALUES ('028_retire_legacy_case_facts.sql');


-- Migration: 029_normalize_case_transaction_amounts.sql
-- Public transaction contract: KRW integer amounts and explicit movement types.
-- This migration intentionally does not add a deduplication key; that rule is
-- defined only after source-event metadata and existing records are audited.
SET @fractional_amounts = (
    SELECT COUNT(*) FROM case_transactions
    WHERE amount <> TRUNCATE(amount, 0)
);
SET @invalid_transaction_types = (
    SELECT COUNT(*) FROM case_transactions
    WHERE transaction_type NOT IN ('TRANSFER_OUT', 'RETURN_IN', 'CANCELLED')
);
SET @contract_guard_sql = IF(
    @fractional_amounts = 0 AND @invalid_transaction_types = 0,
    'SELECT 1',
    'THIS IS INTENTIONALLY INVALID SQL: transaction rows need manual normalization'
);
PREPARE contract_guard_stmt FROM @contract_guard_sql;
EXECUTE contract_guard_stmt;
DEALLOCATE PREPARE contract_guard_stmt;

ALTER TABLE case_transactions
    MODIFY COLUMN amount BIGINT NOT NULL,
    MODIFY COLUMN transaction_type VARCHAR(32) NOT NULL,
    ADD CONSTRAINT chk_case_transactions_type CHECK (
        transaction_type IN ('TRANSFER_OUT', 'RETURN_IN', 'CANCELLED')
    ),
    ADD CONSTRAINT chk_case_transactions_amount CHECK (amount >= 0);

INSERT INTO schema_migrations (migration_name) VALUES ('029_normalize_case_transaction_amounts.sql');
